namespace Sparrow.Numerics
{
    public partial struct Vector<T> where T : struct
    {
        public partial struct Two
        {
            public T x { get => this[0]; }
            public T y { get => this[1]; }

            public Two xx { get => new Two(x, x); }
            public Two xy { get => new Two(x, y); }
            public Two yx { get => new Two(y, x); }
            public Two yy { get => new Two(y, y); }

            public Three xxx { get => new Three(x, x, x); }
            public Three xxy { get => new Three(x, x, y); }
            public Three xyx { get => new Three(x, y, x); }
            public Three xyy { get => new Three(x, y, y); }
            public Three yxx { get => new Three(y, x, x); }
            public Three yxy { get => new Three(y, x, y); }
            public Three yyx { get => new Three(y, y, x); }
            public Three yyy { get => new Three(y, y, y); }

            public Four xxxx { get => new Four(x, x, x, x); }
            public Four xxxy { get => new Four(x, x, x, y); }
            public Four xxyx { get => new Four(x, x, y, x); }
            public Four xxyy { get => new Four(x, x, y, y); }
            public Four xyxx { get => new Four(x, y, x, x); }
            public Four xyxy { get => new Four(x, y, x, y); }
            public Four xyyx { get => new Four(x, y, y, x); }
            public Four xyyy { get => new Four(x, y, y, y); }
            public Four yxxx { get => new Four(y, x, x, x); }
            public Four yxxy { get => new Four(y, x, x, y); }
            public Four yxyx { get => new Four(y, x, y, x); }
            public Four yxyy { get => new Four(y, x, y, y); }
            public Four yyxx { get => new Four(y, y, x, x); }
            public Four yyxy { get => new Four(y, y, x, y); }
            public Four yyyx { get => new Four(y, y, y, x); }
            public Four yyyy { get => new Four(y, y, y, y); }
        }
        public partial struct Three
        {
            public T x { get => this[0]; }
            public T y { get => this[1]; }
            public T z { get => this[2]; }

            public Two xx { get => new Two(x, x); }
            public Two xy { get => new Two(x, y); }
            public Two xz { get => new Two(x, z); }
            public Two yx { get => new Two(y, x); }
            public Two yy { get => new Two(y, y); }
            public Two yz { get => new Two(y, z); }
            public Two zx { get => new Two(z, x); }
            public Two zy { get => new Two(z, y); }
            public Two zz { get => new Two(z, z); }

            public Three xxx { get => new Three(x, x, x); }
            public Three xxy { get => new Three(x, x, y); }
            public Three xxz { get => new Three(x, x, z); }
            public Three xyx { get => new Three(x, y, x); }
            public Three xyy { get => new Three(x, y, y); }
            public Three xyz { get => new Three(x, y, z); }
            public Three xzx { get => new Three(x, z, x); }
            public Three xzy { get => new Three(x, z, y); }
            public Three xzz { get => new Three(x, z, z); }
            public Three yxx { get => new Three(y, x, x); }
            public Three yxy { get => new Three(y, x, y); }
            public Three yxz { get => new Three(y, x, z); }
            public Three yyx { get => new Three(y, y, x); }
            public Three yyy { get => new Three(y, y, y); }
            public Three yyz { get => new Three(y, y, z); }
            public Three yzx { get => new Three(y, z, x); }
            public Three yzy { get => new Three(y, z, y); }
            public Three yzz { get => new Three(y, z, z); }
            public Three zxx { get => new Three(z, x, x); }
            public Three zxy { get => new Three(z, x, y); }
            public Three zxz { get => new Three(z, x, z); }
            public Three zyx { get => new Three(z, y, x); }
            public Three zyy { get => new Three(z, y, y); }
            public Three zyz { get => new Three(z, y, z); }
            public Three zzx { get => new Three(z, z, x); }
            public Three zzy { get => new Three(z, z, y); }
            public Three zzz { get => new Three(z, z, z); }

            public Four xxxx { get => new Four(x, x, x, x); }
            public Four xxxy { get => new Four(x, x, x, y); }
            public Four xxxz { get => new Four(x, x, x, z); }
            public Four xxyx { get => new Four(x, x, y, x); }
            public Four xxyy { get => new Four(x, x, y, y); }
            public Four xxyz { get => new Four(x, x, y, z); }
            public Four xxzx { get => new Four(x, x, z, x); }
            public Four xxzy { get => new Four(x, x, z, y); }
            public Four xxzz { get => new Four(x, x, z, z); }
            public Four xyxx { get => new Four(x, y, x, x); }
            public Four xyxy { get => new Four(x, y, x, y); }
            public Four xyxz { get => new Four(x, y, x, z); }
            public Four xyyx { get => new Four(x, y, y, x); }
            public Four xyyy { get => new Four(x, y, y, y); }
            public Four xyyz { get => new Four(x, y, y, z); }
            public Four xyzx { get => new Four(x, y, z, x); }
            public Four xyzy { get => new Four(x, y, z, y); }
            public Four xyzz { get => new Four(x, y, z, z); }
            public Four xzxx { get => new Four(x, z, x, x); }
            public Four xzxy { get => new Four(x, z, x, y); }
            public Four xzxz { get => new Four(x, z, x, z); }
            public Four xzyx { get => new Four(x, z, y, x); }
            public Four xzyy { get => new Four(x, z, y, y); }
            public Four xzyz { get => new Four(x, z, y, z); }
            public Four xzzx { get => new Four(x, z, z, x); }
            public Four xzzy { get => new Four(x, z, z, y); }
            public Four xzzz { get => new Four(x, z, z, z); }
            public Four yxxx { get => new Four(y, x, x, x); }
            public Four yxxy { get => new Four(y, x, x, y); }
            public Four yxxz { get => new Four(y, x, x, z); }
            public Four yxyx { get => new Four(y, x, y, x); }
            public Four yxyy { get => new Four(y, x, y, y); }
            public Four yxyz { get => new Four(y, x, y, z); }
            public Four yxzx { get => new Four(y, x, z, x); }
            public Four yxzy { get => new Four(y, x, z, y); }
            public Four yxzz { get => new Four(y, x, z, z); }
            public Four yyxx { get => new Four(y, y, x, x); }
            public Four yyxy { get => new Four(y, y, x, y); }
            public Four yyxz { get => new Four(y, y, x, z); }
            public Four yyyx { get => new Four(y, y, y, x); }
            public Four yyyy { get => new Four(y, y, y, y); }
            public Four yyyz { get => new Four(y, y, y, z); }
            public Four yyzx { get => new Four(y, y, z, x); }
            public Four yyzy { get => new Four(y, y, z, y); }
            public Four yyzz { get => new Four(y, y, z, z); }
            public Four yzxx { get => new Four(y, z, x, x); }
            public Four yzxy { get => new Four(y, z, x, y); }
            public Four yzxz { get => new Four(y, z, x, z); }
            public Four yzyx { get => new Four(y, z, y, x); }
            public Four yzyy { get => new Four(y, z, y, y); }
            public Four yzyz { get => new Four(y, z, y, z); }
            public Four yzzx { get => new Four(y, z, z, x); }
            public Four yzzy { get => new Four(y, z, z, y); }
            public Four yzzz { get => new Four(y, z, z, z); }
            public Four zxxx { get => new Four(z, x, x, x); }
            public Four zxxy { get => new Four(z, x, x, y); }
            public Four zxxz { get => new Four(z, x, x, z); }
            public Four zxyx { get => new Four(z, x, y, x); }
            public Four zxyy { get => new Four(z, x, y, y); }
            public Four zxyz { get => new Four(z, x, y, z); }
            public Four zxzx { get => new Four(z, x, z, x); }
            public Four zxzy { get => new Four(z, x, z, y); }
            public Four zxzz { get => new Four(z, x, z, z); }
            public Four zyxx { get => new Four(z, y, x, x); }
            public Four zyxy { get => new Four(z, y, x, y); }
            public Four zyxz { get => new Four(z, y, x, z); }
            public Four zyyx { get => new Four(z, y, y, x); }
            public Four zyyy { get => new Four(z, y, y, y); }
            public Four zyyz { get => new Four(z, y, y, z); }
            public Four zyzx { get => new Four(z, y, z, x); }
            public Four zyzy { get => new Four(z, y, z, y); }
            public Four zyzz { get => new Four(z, y, z, z); }
            public Four zzxx { get => new Four(z, z, x, x); }
            public Four zzxy { get => new Four(z, z, x, y); }
            public Four zzxz { get => new Four(z, z, x, z); }
            public Four zzyx { get => new Four(z, z, y, x); }
            public Four zzyy { get => new Four(z, z, y, y); }
            public Four zzyz { get => new Four(z, z, y, z); }
            public Four zzzx { get => new Four(z, z, z, x); }
            public Four zzzy { get => new Four(z, z, z, y); }
            public Four zzzz { get => new Four(z, z, z, z); }
        }
        public partial struct Four
        {
            public T x { get => this[0]; }
            public T y { get => this[1]; }
            public T z { get => this[2]; }
            public T w { get => this[3]; }

            public Two xx { get => new Two(x, x); }
            public Two xy { get => new Two(x, y); }
            public Two xz { get => new Two(x, z); }
            public Two xw { get => new Two(x, w); }
            public Two yx { get => new Two(y, x); }
            public Two yy { get => new Two(y, y); }
            public Two yz { get => new Two(y, z); }
            public Two yw { get => new Two(y, w); }
            public Two zx { get => new Two(z, x); }
            public Two zy { get => new Two(z, y); }
            public Two zz { get => new Two(z, z); }
            public Two zw { get => new Two(z, w); }
            public Two wx { get => new Two(w, x); }
            public Two wy { get => new Two(w, y); }
            public Two wz { get => new Two(w, z); }
            public Two ww { get => new Two(w, w); }

            public Three xxx { get => new Three(x, x, x); }
            public Three xxy { get => new Three(x, x, y); }
            public Three xxz { get => new Three(x, x, z); }
            public Three xxw { get => new Three(x, x, w); }
            public Three xyx { get => new Three(x, y, x); }
            public Three xyy { get => new Three(x, y, y); }
            public Three xyz { get => new Three(x, y, z); }
            public Three xyw { get => new Three(x, y, w); }
            public Three xzx { get => new Three(x, z, x); }
            public Three xzy { get => new Three(x, z, y); }
            public Three xzz { get => new Three(x, z, z); }
            public Three xzw { get => new Three(x, z, w); }
            public Three xwx { get => new Three(x, w, x); }
            public Three xwy { get => new Three(x, w, y); }
            public Three xwz { get => new Three(x, w, z); }
            public Three xww { get => new Three(x, w, w); }
            public Three yxx { get => new Three(y, x, x); }
            public Three yxy { get => new Three(y, x, y); }
            public Three yxz { get => new Three(y, x, z); }
            public Three yxw { get => new Three(y, x, w); }
            public Three yyx { get => new Three(y, y, x); }
            public Three yyy { get => new Three(y, y, y); }
            public Three yyz { get => new Three(y, y, z); }
            public Three yyw { get => new Three(y, y, w); }
            public Three yzx { get => new Three(y, z, x); }
            public Three yzy { get => new Three(y, z, y); }
            public Three yzz { get => new Three(y, z, z); }
            public Three yzw { get => new Three(y, z, w); }
            public Three ywx { get => new Three(y, w, x); }
            public Three ywy { get => new Three(y, w, y); }
            public Three ywz { get => new Three(y, w, z); }
            public Three yww { get => new Three(y, w, w); }
            public Three zxx { get => new Three(z, x, x); }
            public Three zxy { get => new Three(z, x, y); }
            public Three zxz { get => new Three(z, x, z); }
            public Three zxw { get => new Three(z, x, w); }
            public Three zyx { get => new Three(z, y, x); }
            public Three zyy { get => new Three(z, y, y); }
            public Three zyz { get => new Three(z, y, z); }
            public Three zyw { get => new Three(z, y, w); }
            public Three zzx { get => new Three(z, z, x); }
            public Three zzy { get => new Three(z, z, y); }
            public Three zzz { get => new Three(z, z, z); }
            public Three zzw { get => new Three(z, z, w); }
            public Three zwx { get => new Three(z, w, x); }
            public Three zwy { get => new Three(z, w, y); }
            public Three zwz { get => new Three(z, w, z); }
            public Three zww { get => new Three(z, w, w); }
            public Three wxx { get => new Three(w, x, x); }
            public Three wxy { get => new Three(w, x, y); }
            public Three wxz { get => new Three(w, x, z); }
            public Three wxw { get => new Three(w, x, w); }
            public Three wyx { get => new Three(w, y, x); }
            public Three wyy { get => new Three(w, y, y); }
            public Three wyz { get => new Three(w, y, z); }
            public Three wyw { get => new Three(w, y, w); }
            public Three wzx { get => new Three(w, z, x); }
            public Three wzy { get => new Three(w, z, y); }
            public Three wzz { get => new Three(w, z, z); }
            public Three wzw { get => new Three(w, z, w); }
            public Three wwx { get => new Three(w, w, x); }
            public Three wwy { get => new Three(w, w, y); }
            public Three wwz { get => new Three(w, w, z); }
            public Three www { get => new Three(w, w, w); }

            public Four xxxx { get => new Four(x, x, x, x); }
            public Four xxxy { get => new Four(x, x, x, y); }
            public Four xxxz { get => new Four(x, x, x, z); }
            public Four xxxw { get => new Four(x, x, x, w); }
            public Four xxyx { get => new Four(x, x, y, x); }
            public Four xxyy { get => new Four(x, x, y, y); }
            public Four xxyz { get => new Four(x, x, y, z); }
            public Four xxyw { get => new Four(x, x, y, w); }
            public Four xxzx { get => new Four(x, x, z, x); }
            public Four xxzy { get => new Four(x, x, z, y); }
            public Four xxzz { get => new Four(x, x, z, z); }
            public Four xxzw { get => new Four(x, x, z, w); }
            public Four xxwx { get => new Four(x, x, w, x); }
            public Four xxwy { get => new Four(x, x, w, y); }
            public Four xxwz { get => new Four(x, x, w, z); }
            public Four xxww { get => new Four(x, x, w, w); }
            public Four xyxx { get => new Four(x, y, x, x); }
            public Four xyxy { get => new Four(x, y, x, y); }
            public Four xyxz { get => new Four(x, y, x, z); }
            public Four xyxw { get => new Four(x, y, x, w); }
            public Four xyyx { get => new Four(x, y, y, x); }
            public Four xyyy { get => new Four(x, y, y, y); }
            public Four xyyz { get => new Four(x, y, y, z); }
            public Four xyyw { get => new Four(x, y, y, w); }
            public Four xyzx { get => new Four(x, y, z, x); }
            public Four xyzy { get => new Four(x, y, z, y); }
            public Four xyzz { get => new Four(x, y, z, z); }
            public Four xyzw { get => new Four(x, y, z, w); }
            public Four xywx { get => new Four(x, y, w, x); }
            public Four xywy { get => new Four(x, y, w, y); }
            public Four xywz { get => new Four(x, y, w, z); }
            public Four xyww { get => new Four(x, y, w, w); }
            public Four xzxx { get => new Four(x, z, x, x); }
            public Four xzxy { get => new Four(x, z, x, y); }
            public Four xzxz { get => new Four(x, z, x, z); }
            public Four xzxw { get => new Four(x, z, x, w); }
            public Four xzyx { get => new Four(x, z, y, x); }
            public Four xzyy { get => new Four(x, z, y, y); }
            public Four xzyz { get => new Four(x, z, y, z); }
            public Four xzyw { get => new Four(x, z, y, w); }
            public Four xzzx { get => new Four(x, z, z, x); }
            public Four xzzy { get => new Four(x, z, z, y); }
            public Four xzzz { get => new Four(x, z, z, z); }
            public Four xzzw { get => new Four(x, z, z, w); }
            public Four xzwx { get => new Four(x, z, w, x); }
            public Four xzwy { get => new Four(x, z, w, y); }
            public Four xzwz { get => new Four(x, z, w, z); }
            public Four xzww { get => new Four(x, z, w, w); }
            public Four xwxx { get => new Four(x, w, x, x); }
            public Four xwxy { get => new Four(x, w, x, y); }
            public Four xwxz { get => new Four(x, w, x, z); }
            public Four xwxw { get => new Four(x, w, x, w); }
            public Four xwyx { get => new Four(x, w, y, x); }
            public Four xwyy { get => new Four(x, w, y, y); }
            public Four xwyz { get => new Four(x, w, y, z); }
            public Four xwyw { get => new Four(x, w, y, w); }
            public Four xwzx { get => new Four(x, w, z, x); }
            public Four xwzy { get => new Four(x, w, z, y); }
            public Four xwzz { get => new Four(x, w, z, z); }
            public Four xwzw { get => new Four(x, w, z, w); }
            public Four xwwx { get => new Four(x, w, w, x); }
            public Four xwwy { get => new Four(x, w, w, y); }
            public Four xwwz { get => new Four(x, w, w, z); }
            public Four xwww { get => new Four(x, w, w, w); }
            public Four yxxx { get => new Four(y, x, x, x); }
            public Four yxxy { get => new Four(y, x, x, y); }
            public Four yxxz { get => new Four(y, x, x, z); }
            public Four yxxw { get => new Four(y, x, x, w); }
            public Four yxyx { get => new Four(y, x, y, x); }
            public Four yxyy { get => new Four(y, x, y, y); }
            public Four yxyz { get => new Four(y, x, y, z); }
            public Four yxyw { get => new Four(y, x, y, w); }
            public Four yxzx { get => new Four(y, x, z, x); }
            public Four yxzy { get => new Four(y, x, z, y); }
            public Four yxzz { get => new Four(y, x, z, z); }
            public Four yxzw { get => new Four(y, x, z, w); }
            public Four yxwx { get => new Four(y, x, w, x); }
            public Four yxwy { get => new Four(y, x, w, y); }
            public Four yxwz { get => new Four(y, x, w, z); }
            public Four yxww { get => new Four(y, x, w, w); }
            public Four yyxx { get => new Four(y, y, x, x); }
            public Four yyxy { get => new Four(y, y, x, y); }
            public Four yyxz { get => new Four(y, y, x, z); }
            public Four yyxw { get => new Four(y, y, x, w); }
            public Four yyyx { get => new Four(y, y, y, x); }
            public Four yyyy { get => new Four(y, y, y, y); }
            public Four yyyz { get => new Four(y, y, y, z); }
            public Four yyyw { get => new Four(y, y, y, w); }
            public Four yyzx { get => new Four(y, y, z, x); }
            public Four yyzy { get => new Four(y, y, z, y); }
            public Four yyzz { get => new Four(y, y, z, z); }
            public Four yyzw { get => new Four(y, y, z, w); }
            public Four yywx { get => new Four(y, y, w, x); }
            public Four yywy { get => new Four(y, y, w, y); }
            public Four yywz { get => new Four(y, y, w, z); }
            public Four yyww { get => new Four(y, y, w, w); }
            public Four yzxx { get => new Four(y, z, x, x); }
            public Four yzxy { get => new Four(y, z, x, y); }
            public Four yzxz { get => new Four(y, z, x, z); }
            public Four yzxw { get => new Four(y, z, x, w); }
            public Four yzyx { get => new Four(y, z, y, x); }
            public Four yzyy { get => new Four(y, z, y, y); }
            public Four yzyz { get => new Four(y, z, y, z); }
            public Four yzyw { get => new Four(y, z, y, w); }
            public Four yzzx { get => new Four(y, z, z, x); }
            public Four yzzy { get => new Four(y, z, z, y); }
            public Four yzzz { get => new Four(y, z, z, z); }
            public Four yzzw { get => new Four(y, z, z, w); }
            public Four yzwx { get => new Four(y, z, w, x); }
            public Four yzwy { get => new Four(y, z, w, y); }
            public Four yzwz { get => new Four(y, z, w, z); }
            public Four yzww { get => new Four(y, z, w, w); }
            public Four ywxx { get => new Four(y, w, x, x); }
            public Four ywxy { get => new Four(y, w, x, y); }
            public Four ywxz { get => new Four(y, w, x, z); }
            public Four ywxw { get => new Four(y, w, x, w); }
            public Four ywyx { get => new Four(y, w, y, x); }
            public Four ywyy { get => new Four(y, w, y, y); }
            public Four ywyz { get => new Four(y, w, y, z); }
            public Four ywyw { get => new Four(y, w, y, w); }
            public Four ywzx { get => new Four(y, w, z, x); }
            public Four ywzy { get => new Four(y, w, z, y); }
            public Four ywzz { get => new Four(y, w, z, z); }
            public Four ywzw { get => new Four(y, w, z, w); }
            public Four ywwx { get => new Four(y, w, w, x); }
            public Four ywwy { get => new Four(y, w, w, y); }
            public Four ywwz { get => new Four(y, w, w, z); }
            public Four ywww { get => new Four(y, w, w, w); }
            public Four zxxx { get => new Four(z, x, x, x); }
            public Four zxxy { get => new Four(z, x, x, y); }
            public Four zxxz { get => new Four(z, x, x, z); }
            public Four zxxw { get => new Four(z, x, x, w); }
            public Four zxyx { get => new Four(z, x, y, x); }
            public Four zxyy { get => new Four(z, x, y, y); }
            public Four zxyz { get => new Four(z, x, y, z); }
            public Four zxyw { get => new Four(z, x, y, w); }
            public Four zxzx { get => new Four(z, x, z, x); }
            public Four zxzy { get => new Four(z, x, z, y); }
            public Four zxzz { get => new Four(z, x, z, z); }
            public Four zxzw { get => new Four(z, x, z, w); }
            public Four zxwx { get => new Four(z, x, w, x); }
            public Four zxwy { get => new Four(z, x, w, y); }
            public Four zxwz { get => new Four(z, x, w, z); }
            public Four zxww { get => new Four(z, x, w, w); }
            public Four zyxx { get => new Four(z, y, x, x); }
            public Four zyxy { get => new Four(z, y, x, y); }
            public Four zyxz { get => new Four(z, y, x, z); }
            public Four zyxw { get => new Four(z, y, x, w); }
            public Four zyyx { get => new Four(z, y, y, x); }
            public Four zyyy { get => new Four(z, y, y, y); }
            public Four zyyz { get => new Four(z, y, y, z); }
            public Four zyyw { get => new Four(z, y, y, w); }
            public Four zyzx { get => new Four(z, y, z, x); }
            public Four zyzy { get => new Four(z, y, z, y); }
            public Four zyzz { get => new Four(z, y, z, z); }
            public Four zyzw { get => new Four(z, y, z, w); }
            public Four zywx { get => new Four(z, y, w, x); }
            public Four zywy { get => new Four(z, y, w, y); }
            public Four zywz { get => new Four(z, y, w, z); }
            public Four zyww { get => new Four(z, y, w, w); }
            public Four zzxx { get => new Four(z, z, x, x); }
            public Four zzxy { get => new Four(z, z, x, y); }
            public Four zzxz { get => new Four(z, z, x, z); }
            public Four zzxw { get => new Four(z, z, x, w); }
            public Four zzyx { get => new Four(z, z, y, x); }
            public Four zzyy { get => new Four(z, z, y, y); }
            public Four zzyz { get => new Four(z, z, y, z); }
            public Four zzyw { get => new Four(z, z, y, w); }
            public Four zzzx { get => new Four(z, z, z, x); }
            public Four zzzy { get => new Four(z, z, z, y); }
            public Four zzzz { get => new Four(z, z, z, z); }
            public Four zzzw { get => new Four(z, z, z, w); }
            public Four zzwx { get => new Four(z, z, w, x); }
            public Four zzwy { get => new Four(z, z, w, y); }
            public Four zzwz { get => new Four(z, z, w, z); }
            public Four zzww { get => new Four(z, z, w, w); }
            public Four zwxx { get => new Four(z, w, x, x); }
            public Four zwxy { get => new Four(z, w, x, y); }
            public Four zwxz { get => new Four(z, w, x, z); }
            public Four zwxw { get => new Four(z, w, x, w); }
            public Four zwyx { get => new Four(z, w, y, x); }
            public Four zwyy { get => new Four(z, w, y, y); }
            public Four zwyz { get => new Four(z, w, y, z); }
            public Four zwyw { get => new Four(z, w, y, w); }
            public Four zwzx { get => new Four(z, w, z, x); }
            public Four zwzy { get => new Four(z, w, z, y); }
            public Four zwzz { get => new Four(z, w, z, z); }
            public Four zwzw { get => new Four(z, w, z, w); }
            public Four zwwx { get => new Four(z, w, w, x); }
            public Four zwwy { get => new Four(z, w, w, y); }
            public Four zwwz { get => new Four(z, w, w, z); }
            public Four zwww { get => new Four(z, w, w, w); }
            public Four wxxx { get => new Four(w, x, x, x); }
            public Four wxxy { get => new Four(w, x, x, y); }
            public Four wxxz { get => new Four(w, x, x, z); }
            public Four wxxw { get => new Four(w, x, x, w); }
            public Four wxyx { get => new Four(w, x, y, x); }
            public Four wxyy { get => new Four(w, x, y, y); }
            public Four wxyz { get => new Four(w, x, y, z); }
            public Four wxyw { get => new Four(w, x, y, w); }
            public Four wxzx { get => new Four(w, x, z, x); }
            public Four wxzy { get => new Four(w, x, z, y); }
            public Four wxzz { get => new Four(w, x, z, z); }
            public Four wxzw { get => new Four(w, x, z, w); }
            public Four wxwx { get => new Four(w, x, w, x); }
            public Four wxwy { get => new Four(w, x, w, y); }
            public Four wxwz { get => new Four(w, x, w, z); }
            public Four wxww { get => new Four(w, x, w, w); }
            public Four wyxx { get => new Four(w, y, x, x); }
            public Four wyxy { get => new Four(w, y, x, y); }
            public Four wyxz { get => new Four(w, y, x, z); }
            public Four wyxw { get => new Four(w, y, x, w); }
            public Four wyyx { get => new Four(w, y, y, x); }
            public Four wyyy { get => new Four(w, y, y, y); }
            public Four wyyz { get => new Four(w, y, y, z); }
            public Four wyyw { get => new Four(w, y, y, w); }
            public Four wyzx { get => new Four(w, y, z, x); }
            public Four wyzy { get => new Four(w, y, z, y); }
            public Four wyzz { get => new Four(w, y, z, z); }
            public Four wyzw { get => new Four(w, y, z, w); }
            public Four wywx { get => new Four(w, y, w, x); }
            public Four wywy { get => new Four(w, y, w, y); }
            public Four wywz { get => new Four(w, y, w, z); }
            public Four wyww { get => new Four(w, y, w, w); }
            public Four wzxx { get => new Four(w, z, x, x); }
            public Four wzxy { get => new Four(w, z, x, y); }
            public Four wzxz { get => new Four(w, z, x, z); }
            public Four wzxw { get => new Four(w, z, x, w); }
            public Four wzyx { get => new Four(w, z, y, x); }
            public Four wzyy { get => new Four(w, z, y, y); }
            public Four wzyz { get => new Four(w, z, y, z); }
            public Four wzyw { get => new Four(w, z, y, w); }
            public Four wzzx { get => new Four(w, z, z, x); }
            public Four wzzy { get => new Four(w, z, z, y); }
            public Four wzzz { get => new Four(w, z, z, z); }
            public Four wzzw { get => new Four(w, z, z, w); }
            public Four wzwx { get => new Four(w, z, w, x); }
            public Four wzwy { get => new Four(w, z, w, y); }
            public Four wzwz { get => new Four(w, z, w, z); }
            public Four wzww { get => new Four(w, z, w, w); }
            public Four wwxx { get => new Four(w, w, x, x); }
            public Four wwxy { get => new Four(w, w, x, y); }
            public Four wwxz { get => new Four(w, w, x, z); }
            public Four wwxw { get => new Four(w, w, x, w); }
            public Four wwyx { get => new Four(w, w, y, x); }
            public Four wwyy { get => new Four(w, w, y, y); }
            public Four wwyz { get => new Four(w, w, y, z); }
            public Four wwyw { get => new Four(w, w, y, w); }
            public Four wwzx { get => new Four(w, w, z, x); }
            public Four wwzy { get => new Four(w, w, z, y); }
            public Four wwzz { get => new Four(w, w, z, z); }
            public Four wwzw { get => new Four(w, w, z, w); }
            public Four wwwx { get => new Four(w, w, w, x); }
            public Four wwwy { get => new Four(w, w, w, y); }
            public Four wwwz { get => new Four(w, w, w, z); }
            public Four wwww { get => new Four(w, w, w, w); }
        }
    }
}