namespace Sparrow.Graphics.OpenGL
{
    public enum AccumOp : uint
    {
        Accum = Raw.GL_ACCUM,
        Load = Raw.GL_LOAD,
        Return = Raw.GL_RETURN,
        Mult = Raw.GL_MULT,
        Add = Raw.GL_ADD,
    }
    public enum AttribMask : uint
    {
        AccumBufferBit = Raw.GL_ACCUM_BUFFER_BIT,
        AllAttribBits = Raw.GL_ALL_ATTRIB_BITS,
        ColorBufferBit = Raw.GL_COLOR_BUFFER_BIT,
        CurrentBit = Raw.GL_CURRENT_BIT,
        DepthBufferBit = Raw.GL_DEPTH_BUFFER_BIT,
        EnableBit = Raw.GL_ENABLE_BIT,
        EvalBit = Raw.GL_EVAL_BIT,
        FogBit = Raw.GL_FOG_BIT,
        HintBit = Raw.GL_HINT_BIT,
        LightingBit = Raw.GL_LIGHTING_BIT,
        LineBit = Raw.GL_LINE_BIT,
        ListBit = Raw.GL_LIST_BIT,
        MultisampleBit = Raw.GL_MULTISAMPLE_BIT,
        MultisampleBitThreeDfx = Raw.GL_MULTISAMPLE_BIT_3DFX,
        MultisampleBitArb = Raw.GL_MULTISAMPLE_BIT_ARB,
        MultisampleBitExt = Raw.GL_MULTISAMPLE_BIT_EXT,
        PixelModeBit = Raw.GL_PIXEL_MODE_BIT,
        PointBit = Raw.GL_POINT_BIT,
        PolygonBit = Raw.GL_POLYGON_BIT,
        PolygonStippleBit = Raw.GL_POLYGON_STIPPLE_BIT,
        ScissorBit = Raw.GL_SCISSOR_BIT,
        StencilBufferBit = Raw.GL_STENCIL_BUFFER_BIT,
        TextureBit = Raw.GL_TEXTURE_BIT,
        TransformBit = Raw.GL_TRANSFORM_BIT,
        ViewportBit = Raw.GL_VIEWPORT_BIT,
    }
    public enum AlphaFunction : uint
    {
        Always = Raw.GL_ALWAYS,
        Equal = Raw.GL_EQUAL,
        Gequal = Raw.GL_GEQUAL,
        Greater = Raw.GL_GREATER,
        Lequal = Raw.GL_LEQUAL,
        Less = Raw.GL_LESS,
        Never = Raw.GL_NEVER,
        Notequal = Raw.GL_NOTEQUAL,
    }
    public enum BlendEquationModeEXT : uint
    {
        AlphaMaxSgix = Raw.GL_ALPHA_MAX_SGIX,
        AlphaMinSgix = Raw.GL_ALPHA_MIN_SGIX,
        FuncAddExt = Raw.GL_FUNC_ADD_EXT,
        FuncReverseSubtractExt = Raw.GL_FUNC_REVERSE_SUBTRACT_EXT,
        FuncSubtractExt = Raw.GL_FUNC_SUBTRACT_EXT,
        LogicOp = Raw.GL_LOGIC_OP,
        MaxExt = Raw.GL_MAX_EXT,
        MinExt = Raw.GL_MIN_EXT,
    }
    public enum BlendingFactorDest : uint
    {
        ConstantAlphaExt = Raw.GL_CONSTANT_ALPHA_EXT,
        ConstantColorExt = Raw.GL_CONSTANT_COLOR_EXT,
        DstAlpha = Raw.GL_DST_ALPHA,
        One = Raw.GL_ONE,
        OneMinusConstantAlphaExt = Raw.GL_ONE_MINUS_CONSTANT_ALPHA_EXT,
        OneMinusConstantColorExt = Raw.GL_ONE_MINUS_CONSTANT_COLOR_EXT,
        OneMinusDstAlpha = Raw.GL_ONE_MINUS_DST_ALPHA,
        OneMinusSrcAlpha = Raw.GL_ONE_MINUS_SRC_ALPHA,
        OneMinusSrcColor = Raw.GL_ONE_MINUS_SRC_COLOR,
        SrcAlpha = Raw.GL_SRC_ALPHA,
        SrcColor = Raw.GL_SRC_COLOR,
        Zero = Raw.GL_ZERO,
    }
    public enum BlendingFactorSrc : uint
    {
        ConstantAlphaExt = Raw.GL_CONSTANT_ALPHA_EXT,
        ConstantColorExt = Raw.GL_CONSTANT_COLOR_EXT,
        DstAlpha = Raw.GL_DST_ALPHA,
        DstColor = Raw.GL_DST_COLOR,
        One = Raw.GL_ONE,
        OneMinusConstantAlphaExt = Raw.GL_ONE_MINUS_CONSTANT_ALPHA_EXT,
        OneMinusConstantColorExt = Raw.GL_ONE_MINUS_CONSTANT_COLOR_EXT,
        OneMinusDstAlpha = Raw.GL_ONE_MINUS_DST_ALPHA,
        OneMinusDstColor = Raw.GL_ONE_MINUS_DST_COLOR,
        OneMinusSrcAlpha = Raw.GL_ONE_MINUS_SRC_ALPHA,
        SrcAlpha = Raw.GL_SRC_ALPHA,
        SrcAlphaSaturate = Raw.GL_SRC_ALPHA_SATURATE,
        Zero = Raw.GL_ZERO,
    }
    public enum Boolean : uint
    {
        False = Raw.GL_FALSE,
        True = Raw.GL_TRUE,
    }
    public enum ClearBufferMask : uint
    {
        AccumBufferBit = Raw.GL_ACCUM_BUFFER_BIT,
        ColorBufferBit = Raw.GL_COLOR_BUFFER_BIT,
        CoverageBufferBitNv = Raw.GL_COVERAGE_BUFFER_BIT_NV,
        DepthBufferBit = Raw.GL_DEPTH_BUFFER_BIT,
        StencilBufferBit = Raw.GL_STENCIL_BUFFER_BIT,
    }
    public enum ClientAttribMask : uint
    {
        ClientAllAttribBits = Raw.GL_CLIENT_ALL_ATTRIB_BITS,
        ClientPixelStoreBit = Raw.GL_CLIENT_PIXEL_STORE_BIT,
        ClientVertexArrayBit = Raw.GL_CLIENT_VERTEX_ARRAY_BIT,
    }
    public enum ClipPlaneName : uint
    {
        ClipDistanceZero = Raw.GL_CLIP_DISTANCE0,
        ClipDistanceOne = Raw.GL_CLIP_DISTANCE1,
        ClipDistanceTwo = Raw.GL_CLIP_DISTANCE2,
        ClipDistanceThree = Raw.GL_CLIP_DISTANCE3,
        ClipDistanceFour = Raw.GL_CLIP_DISTANCE4,
        ClipDistanceFive = Raw.GL_CLIP_DISTANCE5,
        ClipDistanceSix = Raw.GL_CLIP_DISTANCE6,
        ClipDistanceSeven = Raw.GL_CLIP_DISTANCE7,
        ClipPlaneZero = Raw.GL_CLIP_PLANE0,
        ClipPlaneOne = Raw.GL_CLIP_PLANE1,
        ClipPlaneTwo = Raw.GL_CLIP_PLANE2,
        ClipPlaneThree = Raw.GL_CLIP_PLANE3,
        ClipPlaneFour = Raw.GL_CLIP_PLANE4,
        ClipPlaneFive = Raw.GL_CLIP_PLANE5,
    }
    public enum ColorMaterialFace : uint
    {
        Back = Raw.GL_BACK,
        Front = Raw.GL_FRONT,
        FrontAndBack = Raw.GL_FRONT_AND_BACK,
    }
    public enum ColorMaterialParameter : uint
    {
        Ambient = Raw.GL_AMBIENT,
        AmbientAndDiffuse = Raw.GL_AMBIENT_AND_DIFFUSE,
        Diffuse = Raw.GL_DIFFUSE,
        Emission = Raw.GL_EMISSION,
        Specular = Raw.GL_SPECULAR,
    }
    public enum ColorPointerType : uint
    {
        Byte = Raw.GL_BYTE,
        Double = Raw.GL_DOUBLE,
        Float = Raw.GL_FLOAT,
        Int = Raw.GL_INT,
        Short = Raw.GL_SHORT,
        UnsignedByte = Raw.GL_UNSIGNED_BYTE,
        UnsignedInt = Raw.GL_UNSIGNED_INT,
        UnsignedShort = Raw.GL_UNSIGNED_SHORT,
    }
    public enum ColorTableParameterPNameSGI : uint
    {
        ColorTableBias = Raw.GL_COLOR_TABLE_BIAS,
        ColorTableBiasSgi = Raw.GL_COLOR_TABLE_BIAS_SGI,
        ColorTableScale = Raw.GL_COLOR_TABLE_SCALE,
        ColorTableScaleSgi = Raw.GL_COLOR_TABLE_SCALE_SGI,
    }
    public enum ColorTableTargetSGI : uint
    {
        ColorTable = Raw.GL_COLOR_TABLE,
        ColorTableSgi = Raw.GL_COLOR_TABLE_SGI,
        PostColorMatrixColorTable = Raw.GL_POST_COLOR_MATRIX_COLOR_TABLE,
        PostColorMatrixColorTableSgi = Raw.GL_POST_COLOR_MATRIX_COLOR_TABLE_SGI,
        PostConvolutionColorTable = Raw.GL_POST_CONVOLUTION_COLOR_TABLE,
        PostConvolutionColorTableSgi = Raw.GL_POST_CONVOLUTION_COLOR_TABLE_SGI,
        ProxyColorTable = Raw.GL_PROXY_COLOR_TABLE,
        ProxyColorTableSgi = Raw.GL_PROXY_COLOR_TABLE_SGI,
        ProxyPostColorMatrixColorTable = Raw.GL_PROXY_POST_COLOR_MATRIX_COLOR_TABLE,
        ProxyPostColorMatrixColorTableSgi = Raw.GL_PROXY_POST_COLOR_MATRIX_COLOR_TABLE_SGI,
        ProxyPostConvolutionColorTable = Raw.GL_PROXY_POST_CONVOLUTION_COLOR_TABLE,
        ProxyPostConvolutionColorTableSgi = Raw.GL_PROXY_POST_CONVOLUTION_COLOR_TABLE_SGI,
        ProxyTextureColorTableSgi = Raw.GL_PROXY_TEXTURE_COLOR_TABLE_SGI,
        TextureColorTableSgi = Raw.GL_TEXTURE_COLOR_TABLE_SGI,
    }
    public enum ContextFlagMask : uint
    {
        ContextFlagDebugBit = Raw.GL_CONTEXT_FLAG_DEBUG_BIT,
        ContextFlagDebugBitKhr = Raw.GL_CONTEXT_FLAG_DEBUG_BIT_KHR,
        ContextFlagForwardCompatibleBit = Raw.GL_CONTEXT_FLAG_FORWARD_COMPATIBLE_BIT,
        ContextFlagRobustAccessBitArb = Raw.GL_CONTEXT_FLAG_ROBUST_ACCESS_BIT_ARB,
    }
    public enum ContextProfileMask : uint
    {
        ContextCompatibilityProfileBit = Raw.GL_CONTEXT_COMPATIBILITY_PROFILE_BIT,
        ContextCoreProfileBit = Raw.GL_CONTEXT_CORE_PROFILE_BIT,
    }
    public enum ConvolutionBorderModeEXT : uint
    {
        Reduce = Raw.GL_REDUCE,
        ReduceExt = Raw.GL_REDUCE_EXT,
    }
    public enum ConvolutionParameterEXT : uint
    {
        ConvolutionBorderMode = Raw.GL_CONVOLUTION_BORDER_MODE,
        ConvolutionBorderModeExt = Raw.GL_CONVOLUTION_BORDER_MODE_EXT,
        ConvolutionFilterBias = Raw.GL_CONVOLUTION_FILTER_BIAS,
        ConvolutionFilterBiasExt = Raw.GL_CONVOLUTION_FILTER_BIAS_EXT,
        ConvolutionFilterScale = Raw.GL_CONVOLUTION_FILTER_SCALE,
        ConvolutionFilterScaleExt = Raw.GL_CONVOLUTION_FILTER_SCALE_EXT,
    }
    public enum ConvolutionTargetEXT : uint
    {
        ConvolutionOneD = Raw.GL_CONVOLUTION_1D,
        ConvolutionOneDExt = Raw.GL_CONVOLUTION_1D_EXT,
        ConvolutionTwoD = Raw.GL_CONVOLUTION_2D,
        ConvolutionTwoDExt = Raw.GL_CONVOLUTION_2D_EXT,
    }
    public enum CullFaceMode : uint
    {
        Back = Raw.GL_BACK,
        Front = Raw.GL_FRONT,
        FrontAndBack = Raw.GL_FRONT_AND_BACK,
    }
    public enum DataType : uint
    {
    }
    public enum DepthFunction : uint
    {
        Always = Raw.GL_ALWAYS,
        Equal = Raw.GL_EQUAL,
        Gequal = Raw.GL_GEQUAL,
        Greater = Raw.GL_GREATER,
        Lequal = Raw.GL_LEQUAL,
        Less = Raw.GL_LESS,
        Never = Raw.GL_NEVER,
        Notequal = Raw.GL_NOTEQUAL,
    }
    public enum DrawBufferMode : uint
    {
        AuxZero = Raw.GL_AUX0,
        AuxOne = Raw.GL_AUX1,
        AuxTwo = Raw.GL_AUX2,
        AuxThree = Raw.GL_AUX3,
        Back = Raw.GL_BACK,
        BackLeft = Raw.GL_BACK_LEFT,
        BackRight = Raw.GL_BACK_RIGHT,
        Front = Raw.GL_FRONT,
        FrontAndBack = Raw.GL_FRONT_AND_BACK,
        FrontLeft = Raw.GL_FRONT_LEFT,
        FrontRight = Raw.GL_FRONT_RIGHT,
        Left = Raw.GL_LEFT,
        None = Raw.GL_NONE,
        NoneOes = Raw.GL_NONE_OES,
        Right = Raw.GL_RIGHT,
    }
    public enum EnableCap : uint
    {
        AlphaTest = Raw.GL_ALPHA_TEST,
        AsyncDrawPixelsSgix = Raw.GL_ASYNC_DRAW_PIXELS_SGIX,
        AsyncHistogramSgix = Raw.GL_ASYNC_HISTOGRAM_SGIX,
        AsyncReadPixelsSgix = Raw.GL_ASYNC_READ_PIXELS_SGIX,
        AsyncTexImageSgix = Raw.GL_ASYNC_TEX_IMAGE_SGIX,
        AutoNormal = Raw.GL_AUTO_NORMAL,
        Blend = Raw.GL_BLEND,
        CalligraphicFragmentSgix = Raw.GL_CALLIGRAPHIC_FRAGMENT_SGIX,
        ClipPlaneZero = Raw.GL_CLIP_PLANE0,
        ClipPlaneOne = Raw.GL_CLIP_PLANE1,
        ClipPlaneTwo = Raw.GL_CLIP_PLANE2,
        ClipPlaneThree = Raw.GL_CLIP_PLANE3,
        ClipPlaneFour = Raw.GL_CLIP_PLANE4,
        ClipPlaneFive = Raw.GL_CLIP_PLANE5,
        ColorArray = Raw.GL_COLOR_ARRAY,
        ColorLogicOp = Raw.GL_COLOR_LOGIC_OP,
        ColorMaterial = Raw.GL_COLOR_MATERIAL,
        ColorTableSgi = Raw.GL_COLOR_TABLE_SGI,
        ConvolutionOneDExt = Raw.GL_CONVOLUTION_1D_EXT,
        ConvolutionTwoDExt = Raw.GL_CONVOLUTION_2D_EXT,
        CullFace = Raw.GL_CULL_FACE,
        DepthTest = Raw.GL_DEPTH_TEST,
        Dither = Raw.GL_DITHER,
        EdgeFlagArray = Raw.GL_EDGE_FLAG_ARRAY,
        Fog = Raw.GL_FOG,
        FogOffsetSgix = Raw.GL_FOG_OFFSET_SGIX,
        FragmentColorMaterialSgix = Raw.GL_FRAGMENT_COLOR_MATERIAL_SGIX,
        FragmentLightZeroSgix = Raw.GL_FRAGMENT_LIGHT0_SGIX,
        FragmentLightOneSgix = Raw.GL_FRAGMENT_LIGHT1_SGIX,
        FragmentLightTwoSgix = Raw.GL_FRAGMENT_LIGHT2_SGIX,
        FragmentLightThreeSgix = Raw.GL_FRAGMENT_LIGHT3_SGIX,
        FragmentLightFourSgix = Raw.GL_FRAGMENT_LIGHT4_SGIX,
        FragmentLightFiveSgix = Raw.GL_FRAGMENT_LIGHT5_SGIX,
        FragmentLightSixSgix = Raw.GL_FRAGMENT_LIGHT6_SGIX,
        FragmentLightSevenSgix = Raw.GL_FRAGMENT_LIGHT7_SGIX,
        FragmentLightingSgix = Raw.GL_FRAGMENT_LIGHTING_SGIX,
        FramezoomSgix = Raw.GL_FRAMEZOOM_SGIX,
        HistogramExt = Raw.GL_HISTOGRAM_EXT,
        IndexArray = Raw.GL_INDEX_ARRAY,
        IndexLogicOp = Raw.GL_INDEX_LOGIC_OP,
        InterlaceSgix = Raw.GL_INTERLACE_SGIX,
        IrInstrumentOneSgix = Raw.GL_IR_INSTRUMENT1_SGIX,
        LightZero = Raw.GL_LIGHT0,
        LightOne = Raw.GL_LIGHT1,
        LightTwo = Raw.GL_LIGHT2,
        LightThree = Raw.GL_LIGHT3,
        LightFour = Raw.GL_LIGHT4,
        LightFive = Raw.GL_LIGHT5,
        LightSix = Raw.GL_LIGHT6,
        LightSeven = Raw.GL_LIGHT7,
        Lighting = Raw.GL_LIGHTING,
        LineSmooth = Raw.GL_LINE_SMOOTH,
        LineStipple = Raw.GL_LINE_STIPPLE,
        MapOneColorFour = Raw.GL_MAP1_COLOR_4,
        MapOneIndex = Raw.GL_MAP1_INDEX,
        MapOneNormal = Raw.GL_MAP1_NORMAL,
        MapOneTextureCoordOne = Raw.GL_MAP1_TEXTURE_COORD_1,
        MapOneTextureCoordTwo = Raw.GL_MAP1_TEXTURE_COORD_2,
        MapOneTextureCoordThree = Raw.GL_MAP1_TEXTURE_COORD_3,
        MapOneTextureCoordFour = Raw.GL_MAP1_TEXTURE_COORD_4,
        MapOneVertexThree = Raw.GL_MAP1_VERTEX_3,
        MapOneVertexFour = Raw.GL_MAP1_VERTEX_4,
        MapTwoColorFour = Raw.GL_MAP2_COLOR_4,
        MapTwoIndex = Raw.GL_MAP2_INDEX,
        MapTwoNormal = Raw.GL_MAP2_NORMAL,
        MapTwoTextureCoordOne = Raw.GL_MAP2_TEXTURE_COORD_1,
        MapTwoTextureCoordTwo = Raw.GL_MAP2_TEXTURE_COORD_2,
        MapTwoTextureCoordThree = Raw.GL_MAP2_TEXTURE_COORD_3,
        MapTwoTextureCoordFour = Raw.GL_MAP2_TEXTURE_COORD_4,
        MapTwoVertexThree = Raw.GL_MAP2_VERTEX_3,
        MapTwoVertexFour = Raw.GL_MAP2_VERTEX_4,
        MinmaxExt = Raw.GL_MINMAX_EXT,
        MultisampleSgis = Raw.GL_MULTISAMPLE_SGIS,
        Normalize = Raw.GL_NORMALIZE,
        NormalArray = Raw.GL_NORMAL_ARRAY,
        PixelTextureSgis = Raw.GL_PIXEL_TEXTURE_SGIS,
        PixelTexGenSgix = Raw.GL_PIXEL_TEX_GEN_SGIX,
        PointSmooth = Raw.GL_POINT_SMOOTH,
        PolygonOffsetFill = Raw.GL_POLYGON_OFFSET_FILL,
        PolygonOffsetLine = Raw.GL_POLYGON_OFFSET_LINE,
        PolygonOffsetPoint = Raw.GL_POLYGON_OFFSET_POINT,
        PolygonSmooth = Raw.GL_POLYGON_SMOOTH,
        PolygonStipple = Raw.GL_POLYGON_STIPPLE,
        PostColorMatrixColorTableSgi = Raw.GL_POST_COLOR_MATRIX_COLOR_TABLE_SGI,
        PostConvolutionColorTableSgi = Raw.GL_POST_CONVOLUTION_COLOR_TABLE_SGI,
        ReferencePlaneSgix = Raw.GL_REFERENCE_PLANE_SGIX,
        RescaleNormalExt = Raw.GL_RESCALE_NORMAL_EXT,
        SampleAlphaToMaskSgis = Raw.GL_SAMPLE_ALPHA_TO_MASK_SGIS,
        SampleAlphaToOneSgis = Raw.GL_SAMPLE_ALPHA_TO_ONE_SGIS,
        SampleMaskSgis = Raw.GL_SAMPLE_MASK_SGIS,
        ScissorTest = Raw.GL_SCISSOR_TEST,
        SeparableTwoDExt = Raw.GL_SEPARABLE_2D_EXT,
        SharedTexturePaletteExt = Raw.GL_SHARED_TEXTURE_PALETTE_EXT,
        SpriteSgix = Raw.GL_SPRITE_SGIX,
        StencilTest = Raw.GL_STENCIL_TEST,
        TextureOneD = Raw.GL_TEXTURE_1D,
        TextureTwoD = Raw.GL_TEXTURE_2D,
        TextureThreeDExt = Raw.GL_TEXTURE_3D_EXT,
        TextureFourDSgis = Raw.GL_TEXTURE_4D_SGIS,
        TextureColorTableSgi = Raw.GL_TEXTURE_COLOR_TABLE_SGI,
        TextureCoordArray = Raw.GL_TEXTURE_COORD_ARRAY,
        TextureGenQ = Raw.GL_TEXTURE_GEN_Q,
        TextureGenR = Raw.GL_TEXTURE_GEN_R,
        TextureGenS = Raw.GL_TEXTURE_GEN_S,
        TextureGenT = Raw.GL_TEXTURE_GEN_T,
        VertexArray = Raw.GL_VERTEX_ARRAY,
    }
    public enum ErrorCode : uint
    {
        InvalidEnum = Raw.GL_INVALID_ENUM,
        InvalidFramebufferOperation = Raw.GL_INVALID_FRAMEBUFFER_OPERATION,
        InvalidFramebufferOperationExt = Raw.GL_INVALID_FRAMEBUFFER_OPERATION_EXT,
        InvalidFramebufferOperationOes = Raw.GL_INVALID_FRAMEBUFFER_OPERATION_OES,
        InvalidOperation = Raw.GL_INVALID_OPERATION,
        InvalidValue = Raw.GL_INVALID_VALUE,
        NoError = Raw.GL_NO_ERROR,
        OutOfMemory = Raw.GL_OUT_OF_MEMORY,
        StackOverflow = Raw.GL_STACK_OVERFLOW,
        StackUnderflow = Raw.GL_STACK_UNDERFLOW,
        TableTooLarge = Raw.GL_TABLE_TOO_LARGE,
        TableTooLargeExt = Raw.GL_TABLE_TOO_LARGE_EXT,
        TextureTooLargeExt = Raw.GL_TEXTURE_TOO_LARGE_EXT,
    }
    public enum FeedbackType : uint
    {
        TwoD = Raw.GL_2D,
        ThreeD = Raw.GL_3D,
        ThreeDColor = Raw.GL_3D_COLOR,
        ThreeDColorTexture = Raw.GL_3D_COLOR_TEXTURE,
        FourDColorTexture = Raw.GL_4D_COLOR_TEXTURE,
    }
    public enum FeedBackToken : uint
    {
        BitmapToken = Raw.GL_BITMAP_TOKEN,
        CopyPixelToken = Raw.GL_COPY_PIXEL_TOKEN,
        DrawPixelToken = Raw.GL_DRAW_PIXEL_TOKEN,
        LineResetToken = Raw.GL_LINE_RESET_TOKEN,
        LineToken = Raw.GL_LINE_TOKEN,
        PassThroughToken = Raw.GL_PASS_THROUGH_TOKEN,
        PointToken = Raw.GL_POINT_TOKEN,
        PolygonToken = Raw.GL_POLYGON_TOKEN,
    }
    public enum FfdMaskSGIX : uint
    {
    }
    public enum FfdTargetSGIX : uint
    {
        GeometryDeformationSgix = Raw.GL_GEOMETRY_DEFORMATION_SGIX,
        TextureDeformationSgix = Raw.GL_TEXTURE_DEFORMATION_SGIX,
    }
    public enum FogCoordinatePointerType : uint
    {
        Float = Raw.GL_FLOAT,
        Double = Raw.GL_DOUBLE,
    }
    public enum FogMode : uint
    {
        Exp = Raw.GL_EXP,
        ExpTwo = Raw.GL_EXP2,
        FogFuncSgis = Raw.GL_FOG_FUNC_SGIS,
        Linear = Raw.GL_LINEAR,
    }
    public enum FogParameter : uint
    {
        FogColor = Raw.GL_FOG_COLOR,
        FogDensity = Raw.GL_FOG_DENSITY,
        FogEnd = Raw.GL_FOG_END,
        FogIndex = Raw.GL_FOG_INDEX,
        FogMode = Raw.GL_FOG_MODE,
        FogOffsetValueSgix = Raw.GL_FOG_OFFSET_VALUE_SGIX,
        FogStart = Raw.GL_FOG_START,
    }
    public enum FogPointerTypeEXT : uint
    {
        Float = Raw.GL_FLOAT,
        Double = Raw.GL_DOUBLE,
    }
    public enum FogPointerTypeIBM : uint
    {
        Float = Raw.GL_FLOAT,
        Double = Raw.GL_DOUBLE,
    }
    public enum FragmentLightModelParameterSGIX : uint
    {
        FragmentLightModelAmbientSgix = Raw.GL_FRAGMENT_LIGHT_MODEL_AMBIENT_SGIX,
        FragmentLightModelLocalViewerSgix = Raw.GL_FRAGMENT_LIGHT_MODEL_LOCAL_VIEWER_SGIX,
        FragmentLightModelNormalInterpolationSgix = Raw.GL_FRAGMENT_LIGHT_MODEL_NORMAL_INTERPOLATION_SGIX,
        FragmentLightModelTwoSideSgix = Raw.GL_FRAGMENT_LIGHT_MODEL_TWO_SIDE_SGIX,
    }
    public enum FrontFaceDirection : uint
    {
        Ccw = Raw.GL_CCW,
        Cw = Raw.GL_CW,
    }
    public enum GetColorTableParameterPNameSGI : uint
    {
        ColorTableAlphaSizeSgi = Raw.GL_COLOR_TABLE_ALPHA_SIZE_SGI,
        ColorTableBiasSgi = Raw.GL_COLOR_TABLE_BIAS_SGI,
        ColorTableBlueSizeSgi = Raw.GL_COLOR_TABLE_BLUE_SIZE_SGI,
        ColorTableFormatSgi = Raw.GL_COLOR_TABLE_FORMAT_SGI,
        ColorTableGreenSizeSgi = Raw.GL_COLOR_TABLE_GREEN_SIZE_SGI,
        ColorTableIntensitySizeSgi = Raw.GL_COLOR_TABLE_INTENSITY_SIZE_SGI,
        ColorTableLuminanceSizeSgi = Raw.GL_COLOR_TABLE_LUMINANCE_SIZE_SGI,
        ColorTableRedSizeSgi = Raw.GL_COLOR_TABLE_RED_SIZE_SGI,
        ColorTableScaleSgi = Raw.GL_COLOR_TABLE_SCALE_SGI,
        ColorTableWidthSgi = Raw.GL_COLOR_TABLE_WIDTH_SGI,
    }
    public enum GetConvolutionParameter : uint
    {
        ConvolutionBorderModeExt = Raw.GL_CONVOLUTION_BORDER_MODE_EXT,
        ConvolutionFilterBiasExt = Raw.GL_CONVOLUTION_FILTER_BIAS_EXT,
        ConvolutionFilterScaleExt = Raw.GL_CONVOLUTION_FILTER_SCALE_EXT,
        ConvolutionFormatExt = Raw.GL_CONVOLUTION_FORMAT_EXT,
        ConvolutionHeightExt = Raw.GL_CONVOLUTION_HEIGHT_EXT,
        ConvolutionWidthExt = Raw.GL_CONVOLUTION_WIDTH_EXT,
        MaxConvolutionHeightExt = Raw.GL_MAX_CONVOLUTION_HEIGHT_EXT,
        MaxConvolutionWidthExt = Raw.GL_MAX_CONVOLUTION_WIDTH_EXT,
    }
    public enum GetHistogramParameterPNameEXT : uint
    {
        HistogramAlphaSizeExt = Raw.GL_HISTOGRAM_ALPHA_SIZE_EXT,
        HistogramBlueSizeExt = Raw.GL_HISTOGRAM_BLUE_SIZE_EXT,
        HistogramFormatExt = Raw.GL_HISTOGRAM_FORMAT_EXT,
        HistogramGreenSizeExt = Raw.GL_HISTOGRAM_GREEN_SIZE_EXT,
        HistogramLuminanceSizeExt = Raw.GL_HISTOGRAM_LUMINANCE_SIZE_EXT,
        HistogramRedSizeExt = Raw.GL_HISTOGRAM_RED_SIZE_EXT,
        HistogramSinkExt = Raw.GL_HISTOGRAM_SINK_EXT,
        HistogramWidthExt = Raw.GL_HISTOGRAM_WIDTH_EXT,
    }
    public enum GetMapQuery : uint
    {
        Coeff = Raw.GL_COEFF,
        Domain = Raw.GL_DOMAIN,
        Order = Raw.GL_ORDER,
    }
    public enum GetMinmaxParameterPNameEXT : uint
    {
        MinmaxFormat = Raw.GL_MINMAX_FORMAT,
        MinmaxFormatExt = Raw.GL_MINMAX_FORMAT_EXT,
        MinmaxSink = Raw.GL_MINMAX_SINK,
        MinmaxSinkExt = Raw.GL_MINMAX_SINK_EXT,
    }
    public enum GetPixelMap : uint
    {
        PixelMapAToA = Raw.GL_PIXEL_MAP_A_TO_A,
        PixelMapBToB = Raw.GL_PIXEL_MAP_B_TO_B,
        PixelMapGToG = Raw.GL_PIXEL_MAP_G_TO_G,
        PixelMapIToA = Raw.GL_PIXEL_MAP_I_TO_A,
        PixelMapIToB = Raw.GL_PIXEL_MAP_I_TO_B,
        PixelMapIToG = Raw.GL_PIXEL_MAP_I_TO_G,
        PixelMapIToI = Raw.GL_PIXEL_MAP_I_TO_I,
        PixelMapIToR = Raw.GL_PIXEL_MAP_I_TO_R,
        PixelMapRToR = Raw.GL_PIXEL_MAP_R_TO_R,
        PixelMapSToS = Raw.GL_PIXEL_MAP_S_TO_S,
    }
    public enum GetPName : uint
    {
        AccumAlphaBits = Raw.GL_ACCUM_ALPHA_BITS,
        AccumBlueBits = Raw.GL_ACCUM_BLUE_BITS,
        AccumClearValue = Raw.GL_ACCUM_CLEAR_VALUE,
        AccumGreenBits = Raw.GL_ACCUM_GREEN_BITS,
        AccumRedBits = Raw.GL_ACCUM_RED_BITS,
        AliasedLineWidthRange = Raw.GL_ALIASED_LINE_WIDTH_RANGE,
        AliasedPointSizeRange = Raw.GL_ALIASED_POINT_SIZE_RANGE,
        AlphaBias = Raw.GL_ALPHA_BIAS,
        AlphaBits = Raw.GL_ALPHA_BITS,
        AlphaScale = Raw.GL_ALPHA_SCALE,
        AlphaTest = Raw.GL_ALPHA_TEST,
        AlphaTestFunc = Raw.GL_ALPHA_TEST_FUNC,
        AlphaTestFuncQcom = Raw.GL_ALPHA_TEST_FUNC_QCOM,
        AlphaTestQcom = Raw.GL_ALPHA_TEST_QCOM,
        AlphaTestRef = Raw.GL_ALPHA_TEST_REF,
        AlphaTestRefQcom = Raw.GL_ALPHA_TEST_REF_QCOM,
        AsyncDrawPixelsSgix = Raw.GL_ASYNC_DRAW_PIXELS_SGIX,
        AsyncHistogramSgix = Raw.GL_ASYNC_HISTOGRAM_SGIX,
        AsyncMarkerSgix = Raw.GL_ASYNC_MARKER_SGIX,
        AsyncReadPixelsSgix = Raw.GL_ASYNC_READ_PIXELS_SGIX,
        AsyncTexImageSgix = Raw.GL_ASYNC_TEX_IMAGE_SGIX,
        AttribStackDepth = Raw.GL_ATTRIB_STACK_DEPTH,
        AutoNormal = Raw.GL_AUTO_NORMAL,
        AuxBuffers = Raw.GL_AUX_BUFFERS,
        Blend = Raw.GL_BLEND,
        BlendColorExt = Raw.GL_BLEND_COLOR_EXT,
        BlendDst = Raw.GL_BLEND_DST,
        BlendEquationExt = Raw.GL_BLEND_EQUATION_EXT,
        BlendSrc = Raw.GL_BLEND_SRC,
        BlueBias = Raw.GL_BLUE_BIAS,
        BlueBits = Raw.GL_BLUE_BITS,
        BlueScale = Raw.GL_BLUE_SCALE,
        CalligraphicFragmentSgix = Raw.GL_CALLIGRAPHIC_FRAGMENT_SGIX,
        ClientAttribStackDepth = Raw.GL_CLIENT_ATTRIB_STACK_DEPTH,
        ClipPlaneZero = Raw.GL_CLIP_PLANE0,
        ClipPlaneOne = Raw.GL_CLIP_PLANE1,
        ClipPlaneTwo = Raw.GL_CLIP_PLANE2,
        ClipPlaneThree = Raw.GL_CLIP_PLANE3,
        ClipPlaneFour = Raw.GL_CLIP_PLANE4,
        ClipPlaneFive = Raw.GL_CLIP_PLANE5,
        ColorArray = Raw.GL_COLOR_ARRAY,
        ColorArrayCountExt = Raw.GL_COLOR_ARRAY_COUNT_EXT,
        ColorArraySize = Raw.GL_COLOR_ARRAY_SIZE,
        ColorArrayStride = Raw.GL_COLOR_ARRAY_STRIDE,
        ColorArrayType = Raw.GL_COLOR_ARRAY_TYPE,
        ColorClearValue = Raw.GL_COLOR_CLEAR_VALUE,
        ColorLogicOp = Raw.GL_COLOR_LOGIC_OP,
        ColorMaterial = Raw.GL_COLOR_MATERIAL,
        ColorMaterialFace = Raw.GL_COLOR_MATERIAL_FACE,
        ColorMaterialParameter = Raw.GL_COLOR_MATERIAL_PARAMETER,
        ColorMatrixSgi = Raw.GL_COLOR_MATRIX_SGI,
        ColorMatrixStackDepthSgi = Raw.GL_COLOR_MATRIX_STACK_DEPTH_SGI,
        ColorTableSgi = Raw.GL_COLOR_TABLE_SGI,
        ColorWritemask = Raw.GL_COLOR_WRITEMASK,
        ConvolutionOneDExt = Raw.GL_CONVOLUTION_1D_EXT,
        ConvolutionTwoDExt = Raw.GL_CONVOLUTION_2D_EXT,
        ConvolutionHintSgix = Raw.GL_CONVOLUTION_HINT_SGIX,
        CullFace = Raw.GL_CULL_FACE,
        CullFaceMode = Raw.GL_CULL_FACE_MODE,
        CurrentColor = Raw.GL_CURRENT_COLOR,
        CurrentIndex = Raw.GL_CURRENT_INDEX,
        CurrentNormal = Raw.GL_CURRENT_NORMAL,
        CurrentRasterColor = Raw.GL_CURRENT_RASTER_COLOR,
        CurrentRasterDistance = Raw.GL_CURRENT_RASTER_DISTANCE,
        CurrentRasterIndex = Raw.GL_CURRENT_RASTER_INDEX,
        CurrentRasterPosition = Raw.GL_CURRENT_RASTER_POSITION,
        CurrentRasterPositionValid = Raw.GL_CURRENT_RASTER_POSITION_VALID,
        CurrentRasterTextureCoords = Raw.GL_CURRENT_RASTER_TEXTURE_COORDS,
        CurrentTextureCoords = Raw.GL_CURRENT_TEXTURE_COORDS,
        DeformationsMaskSgix = Raw.GL_DEFORMATIONS_MASK_SGIX,
        DepthBias = Raw.GL_DEPTH_BIAS,
        DepthBits = Raw.GL_DEPTH_BITS,
        DepthClearValue = Raw.GL_DEPTH_CLEAR_VALUE,
        DepthFunc = Raw.GL_DEPTH_FUNC,
        DepthRange = Raw.GL_DEPTH_RANGE,
        DepthScale = Raw.GL_DEPTH_SCALE,
        DepthTest = Raw.GL_DEPTH_TEST,
        DepthWritemask = Raw.GL_DEPTH_WRITEMASK,
        DetailTextureTwoDBindingSgis = Raw.GL_DETAIL_TEXTURE_2D_BINDING_SGIS,
        DistanceAttenuationSgis = Raw.GL_DISTANCE_ATTENUATION_SGIS,
        Dither = Raw.GL_DITHER,
        Doublebuffer = Raw.GL_DOUBLEBUFFER,
        DrawBuffer = Raw.GL_DRAW_BUFFER,
        DrawBufferExt = Raw.GL_DRAW_BUFFER_EXT,
        EdgeFlag = Raw.GL_EDGE_FLAG,
        EdgeFlagArray = Raw.GL_EDGE_FLAG_ARRAY,
        EdgeFlagArrayCountExt = Raw.GL_EDGE_FLAG_ARRAY_COUNT_EXT,
        EdgeFlagArrayStride = Raw.GL_EDGE_FLAG_ARRAY_STRIDE,
        FeedbackBufferSize = Raw.GL_FEEDBACK_BUFFER_SIZE,
        FeedbackBufferType = Raw.GL_FEEDBACK_BUFFER_TYPE,
        Fog = Raw.GL_FOG,
        FogColor = Raw.GL_FOG_COLOR,
        FogDensity = Raw.GL_FOG_DENSITY,
        FogEnd = Raw.GL_FOG_END,
        FogFuncPointsSgis = Raw.GL_FOG_FUNC_POINTS_SGIS,
        FogHint = Raw.GL_FOG_HINT,
        FogIndex = Raw.GL_FOG_INDEX,
        FogMode = Raw.GL_FOG_MODE,
        FogOffsetSgix = Raw.GL_FOG_OFFSET_SGIX,
        FogOffsetValueSgix = Raw.GL_FOG_OFFSET_VALUE_SGIX,
        FogStart = Raw.GL_FOG_START,
        FragmentColorMaterialFaceSgix = Raw.GL_FRAGMENT_COLOR_MATERIAL_FACE_SGIX,
        FragmentColorMaterialParameterSgix = Raw.GL_FRAGMENT_COLOR_MATERIAL_PARAMETER_SGIX,
        FragmentColorMaterialSgix = Raw.GL_FRAGMENT_COLOR_MATERIAL_SGIX,
        FragmentLightZeroSgix = Raw.GL_FRAGMENT_LIGHT0_SGIX,
        FragmentLightingSgix = Raw.GL_FRAGMENT_LIGHTING_SGIX,
        FragmentLightModelAmbientSgix = Raw.GL_FRAGMENT_LIGHT_MODEL_AMBIENT_SGIX,
        FragmentLightModelLocalViewerSgix = Raw.GL_FRAGMENT_LIGHT_MODEL_LOCAL_VIEWER_SGIX,
        FragmentLightModelNormalInterpolationSgix = Raw.GL_FRAGMENT_LIGHT_MODEL_NORMAL_INTERPOLATION_SGIX,
        FragmentLightModelTwoSideSgix = Raw.GL_FRAGMENT_LIGHT_MODEL_TWO_SIDE_SGIX,
        FramezoomFactorSgix = Raw.GL_FRAMEZOOM_FACTOR_SGIX,
        FramezoomSgix = Raw.GL_FRAMEZOOM_SGIX,
        FrontFace = Raw.GL_FRONT_FACE,
        GenerateMipmapHintSgis = Raw.GL_GENERATE_MIPMAP_HINT_SGIS,
        GreenBias = Raw.GL_GREEN_BIAS,
        GreenBits = Raw.GL_GREEN_BITS,
        GreenScale = Raw.GL_GREEN_SCALE,
        HistogramExt = Raw.GL_HISTOGRAM_EXT,
        IndexArray = Raw.GL_INDEX_ARRAY,
        IndexArrayCountExt = Raw.GL_INDEX_ARRAY_COUNT_EXT,
        IndexArrayStride = Raw.GL_INDEX_ARRAY_STRIDE,
        IndexArrayType = Raw.GL_INDEX_ARRAY_TYPE,
        IndexBits = Raw.GL_INDEX_BITS,
        IndexClearValue = Raw.GL_INDEX_CLEAR_VALUE,
        IndexLogicOp = Raw.GL_INDEX_LOGIC_OP,
        IndexMode = Raw.GL_INDEX_MODE,
        IndexOffset = Raw.GL_INDEX_OFFSET,
        IndexShift = Raw.GL_INDEX_SHIFT,
        IndexWritemask = Raw.GL_INDEX_WRITEMASK,
        InstrumentMeasurementsSgix = Raw.GL_INSTRUMENT_MEASUREMENTS_SGIX,
        InterlaceSgix = Raw.GL_INTERLACE_SGIX,
        IrInstrumentOneSgix = Raw.GL_IR_INSTRUMENT1_SGIX,
        LightZero = Raw.GL_LIGHT0,
        LightOne = Raw.GL_LIGHT1,
        LightTwo = Raw.GL_LIGHT2,
        LightThree = Raw.GL_LIGHT3,
        LightFour = Raw.GL_LIGHT4,
        LightFive = Raw.GL_LIGHT5,
        LightSix = Raw.GL_LIGHT6,
        LightSeven = Raw.GL_LIGHT7,
        Lighting = Raw.GL_LIGHTING,
        LightEnvModeSgix = Raw.GL_LIGHT_ENV_MODE_SGIX,
        LightModelAmbient = Raw.GL_LIGHT_MODEL_AMBIENT,
        LightModelColorControl = Raw.GL_LIGHT_MODEL_COLOR_CONTROL,
        LightModelLocalViewer = Raw.GL_LIGHT_MODEL_LOCAL_VIEWER,
        LightModelTwoSide = Raw.GL_LIGHT_MODEL_TWO_SIDE,
        LineSmooth = Raw.GL_LINE_SMOOTH,
        LineSmoothHint = Raw.GL_LINE_SMOOTH_HINT,
        LineStipple = Raw.GL_LINE_STIPPLE,
        LineStipplePattern = Raw.GL_LINE_STIPPLE_PATTERN,
        LineStippleRepeat = Raw.GL_LINE_STIPPLE_REPEAT,
        LineWidth = Raw.GL_LINE_WIDTH,
        LineWidthGranularity = Raw.GL_LINE_WIDTH_GRANULARITY,
        LineWidthRange = Raw.GL_LINE_WIDTH_RANGE,
        ListBase = Raw.GL_LIST_BASE,
        ListIndex = Raw.GL_LIST_INDEX,
        ListMode = Raw.GL_LIST_MODE,
        LogicOp = Raw.GL_LOGIC_OP,
        LogicOpMode = Raw.GL_LOGIC_OP_MODE,
        MapOneColorFour = Raw.GL_MAP1_COLOR_4,
        MapOneGridDomain = Raw.GL_MAP1_GRID_DOMAIN,
        MapOneGridSegments = Raw.GL_MAP1_GRID_SEGMENTS,
        MapOneIndex = Raw.GL_MAP1_INDEX,
        MapOneNormal = Raw.GL_MAP1_NORMAL,
        MapOneTextureCoordOne = Raw.GL_MAP1_TEXTURE_COORD_1,
        MapOneTextureCoordTwo = Raw.GL_MAP1_TEXTURE_COORD_2,
        MapOneTextureCoordThree = Raw.GL_MAP1_TEXTURE_COORD_3,
        MapOneTextureCoordFour = Raw.GL_MAP1_TEXTURE_COORD_4,
        MapOneVertexThree = Raw.GL_MAP1_VERTEX_3,
        MapOneVertexFour = Raw.GL_MAP1_VERTEX_4,
        MapTwoColorFour = Raw.GL_MAP2_COLOR_4,
        MapTwoGridDomain = Raw.GL_MAP2_GRID_DOMAIN,
        MapTwoGridSegments = Raw.GL_MAP2_GRID_SEGMENTS,
        MapTwoIndex = Raw.GL_MAP2_INDEX,
        MapTwoNormal = Raw.GL_MAP2_NORMAL,
        MapTwoTextureCoordOne = Raw.GL_MAP2_TEXTURE_COORD_1,
        MapTwoTextureCoordTwo = Raw.GL_MAP2_TEXTURE_COORD_2,
        MapTwoTextureCoordThree = Raw.GL_MAP2_TEXTURE_COORD_3,
        MapTwoTextureCoordFour = Raw.GL_MAP2_TEXTURE_COORD_4,
        MapTwoVertexThree = Raw.GL_MAP2_VERTEX_3,
        MapTwoVertexFour = Raw.GL_MAP2_VERTEX_4,
        MapColor = Raw.GL_MAP_COLOR,
        MapStencil = Raw.GL_MAP_STENCIL,
        MatrixMode = Raw.GL_MATRIX_MODE,
        MaxThreeDTextureSizeExt = Raw.GL_MAX_3D_TEXTURE_SIZE_EXT,
        MaxFourDTextureSizeSgis = Raw.GL_MAX_4D_TEXTURE_SIZE_SGIS,
        MaxActiveLightsSgix = Raw.GL_MAX_ACTIVE_LIGHTS_SGIX,
        MaxAsyncDrawPixelsSgix = Raw.GL_MAX_ASYNC_DRAW_PIXELS_SGIX,
        MaxAsyncHistogramSgix = Raw.GL_MAX_ASYNC_HISTOGRAM_SGIX,
        MaxAsyncReadPixelsSgix = Raw.GL_MAX_ASYNC_READ_PIXELS_SGIX,
        MaxAsyncTexImageSgix = Raw.GL_MAX_ASYNC_TEX_IMAGE_SGIX,
        MaxAttribStackDepth = Raw.GL_MAX_ATTRIB_STACK_DEPTH,
        MaxClientAttribStackDepth = Raw.GL_MAX_CLIENT_ATTRIB_STACK_DEPTH,
        MaxClipmapDepthSgix = Raw.GL_MAX_CLIPMAP_DEPTH_SGIX,
        MaxClipmapVirtualDepthSgix = Raw.GL_MAX_CLIPMAP_VIRTUAL_DEPTH_SGIX,
        MaxClipDistances = Raw.GL_MAX_CLIP_DISTANCES,
        MaxClipPlanes = Raw.GL_MAX_CLIP_PLANES,
        MaxColorMatrixStackDepthSgi = Raw.GL_MAX_COLOR_MATRIX_STACK_DEPTH_SGI,
        MaxEvalOrder = Raw.GL_MAX_EVAL_ORDER,
        MaxFogFuncPointsSgis = Raw.GL_MAX_FOG_FUNC_POINTS_SGIS,
        MaxFragmentLightsSgix = Raw.GL_MAX_FRAGMENT_LIGHTS_SGIX,
        MaxFramezoomFactorSgix = Raw.GL_MAX_FRAMEZOOM_FACTOR_SGIX,
        MaxLights = Raw.GL_MAX_LIGHTS,
        MaxListNesting = Raw.GL_MAX_LIST_NESTING,
        MaxModelviewStackDepth = Raw.GL_MAX_MODELVIEW_STACK_DEPTH,
        MaxNameStackDepth = Raw.GL_MAX_NAME_STACK_DEPTH,
        MaxPixelMapTable = Raw.GL_MAX_PIXEL_MAP_TABLE,
        MaxProjectionStackDepth = Raw.GL_MAX_PROJECTION_STACK_DEPTH,
        MaxTextureSize = Raw.GL_MAX_TEXTURE_SIZE,
        MaxTextureStackDepth = Raw.GL_MAX_TEXTURE_STACK_DEPTH,
        MaxViewportDims = Raw.GL_MAX_VIEWPORT_DIMS,
        MinmaxExt = Raw.GL_MINMAX_EXT,
        ModelviewZeroMatrixExt = Raw.GL_MODELVIEW0_MATRIX_EXT,
        ModelviewZeroStackDepthExt = Raw.GL_MODELVIEW0_STACK_DEPTH_EXT,
        ModelviewMatrix = Raw.GL_MODELVIEW_MATRIX,
        ModelviewStackDepth = Raw.GL_MODELVIEW_STACK_DEPTH,
        MultisampleSgis = Raw.GL_MULTISAMPLE_SGIS,
        NameStackDepth = Raw.GL_NAME_STACK_DEPTH,
        Normalize = Raw.GL_NORMALIZE,
        NormalArray = Raw.GL_NORMAL_ARRAY,
        NormalArrayCountExt = Raw.GL_NORMAL_ARRAY_COUNT_EXT,
        NormalArrayStride = Raw.GL_NORMAL_ARRAY_STRIDE,
        NormalArrayType = Raw.GL_NORMAL_ARRAY_TYPE,
        PackAlignment = Raw.GL_PACK_ALIGNMENT,
        PackCmykHintExt = Raw.GL_PACK_CMYK_HINT_EXT,
        PackImageDepthSgis = Raw.GL_PACK_IMAGE_DEPTH_SGIS,
        PackImageHeightExt = Raw.GL_PACK_IMAGE_HEIGHT_EXT,
        PackLsbFirst = Raw.GL_PACK_LSB_FIRST,
        PackResampleSgix = Raw.GL_PACK_RESAMPLE_SGIX,
        PackRowLength = Raw.GL_PACK_ROW_LENGTH,
        PackSkipImagesExt = Raw.GL_PACK_SKIP_IMAGES_EXT,
        PackSkipPixels = Raw.GL_PACK_SKIP_PIXELS,
        PackSkipRows = Raw.GL_PACK_SKIP_ROWS,
        PackSkipVolumesSgis = Raw.GL_PACK_SKIP_VOLUMES_SGIS,
        PackSubsampleRateSgix = Raw.GL_PACK_SUBSAMPLE_RATE_SGIX,
        PackSwapBytes = Raw.GL_PACK_SWAP_BYTES,
        PerspectiveCorrectionHint = Raw.GL_PERSPECTIVE_CORRECTION_HINT,
        PixelMapAToASize = Raw.GL_PIXEL_MAP_A_TO_A_SIZE,
        PixelMapBToBSize = Raw.GL_PIXEL_MAP_B_TO_B_SIZE,
        PixelMapGToGSize = Raw.GL_PIXEL_MAP_G_TO_G_SIZE,
        PixelMapIToASize = Raw.GL_PIXEL_MAP_I_TO_A_SIZE,
        PixelMapIToBSize = Raw.GL_PIXEL_MAP_I_TO_B_SIZE,
        PixelMapIToGSize = Raw.GL_PIXEL_MAP_I_TO_G_SIZE,
        PixelMapIToISize = Raw.GL_PIXEL_MAP_I_TO_I_SIZE,
        PixelMapIToRSize = Raw.GL_PIXEL_MAP_I_TO_R_SIZE,
        PixelMapRToRSize = Raw.GL_PIXEL_MAP_R_TO_R_SIZE,
        PixelMapSToSSize = Raw.GL_PIXEL_MAP_S_TO_S_SIZE,
        PixelTextureSgis = Raw.GL_PIXEL_TEXTURE_SGIS,
        PixelTexGenModeSgix = Raw.GL_PIXEL_TEX_GEN_MODE_SGIX,
        PixelTexGenSgix = Raw.GL_PIXEL_TEX_GEN_SGIX,
        PixelTileBestAlignmentSgix = Raw.GL_PIXEL_TILE_BEST_ALIGNMENT_SGIX,
        PixelTileCacheIncrementSgix = Raw.GL_PIXEL_TILE_CACHE_INCREMENT_SGIX,
        PixelTileCacheSizeSgix = Raw.GL_PIXEL_TILE_CACHE_SIZE_SGIX,
        PixelTileGridDepthSgix = Raw.GL_PIXEL_TILE_GRID_DEPTH_SGIX,
        PixelTileGridHeightSgix = Raw.GL_PIXEL_TILE_GRID_HEIGHT_SGIX,
        PixelTileGridWidthSgix = Raw.GL_PIXEL_TILE_GRID_WIDTH_SGIX,
        PixelTileHeightSgix = Raw.GL_PIXEL_TILE_HEIGHT_SGIX,
        PixelTileWidthSgix = Raw.GL_PIXEL_TILE_WIDTH_SGIX,
        PointFadeThresholdSizeSgis = Raw.GL_POINT_FADE_THRESHOLD_SIZE_SGIS,
        PointSize = Raw.GL_POINT_SIZE,
        PointSizeGranularity = Raw.GL_POINT_SIZE_GRANULARITY,
        PointSizeMaxSgis = Raw.GL_POINT_SIZE_MAX_SGIS,
        PointSizeMinSgis = Raw.GL_POINT_SIZE_MIN_SGIS,
        PointSizeRange = Raw.GL_POINT_SIZE_RANGE,
        PointSmooth = Raw.GL_POINT_SMOOTH,
        PointSmoothHint = Raw.GL_POINT_SMOOTH_HINT,
        PolygonMode = Raw.GL_POLYGON_MODE,
        PolygonOffsetBiasExt = Raw.GL_POLYGON_OFFSET_BIAS_EXT,
        PolygonOffsetFactor = Raw.GL_POLYGON_OFFSET_FACTOR,
        PolygonOffsetFill = Raw.GL_POLYGON_OFFSET_FILL,
        PolygonOffsetLine = Raw.GL_POLYGON_OFFSET_LINE,
        PolygonOffsetPoint = Raw.GL_POLYGON_OFFSET_POINT,
        PolygonOffsetUnits = Raw.GL_POLYGON_OFFSET_UNITS,
        PolygonSmooth = Raw.GL_POLYGON_SMOOTH,
        PolygonSmoothHint = Raw.GL_POLYGON_SMOOTH_HINT,
        PolygonStipple = Raw.GL_POLYGON_STIPPLE,
        PostColorMatrixAlphaBiasSgi = Raw.GL_POST_COLOR_MATRIX_ALPHA_BIAS_SGI,
        PostColorMatrixAlphaScaleSgi = Raw.GL_POST_COLOR_MATRIX_ALPHA_SCALE_SGI,
        PostColorMatrixBlueBiasSgi = Raw.GL_POST_COLOR_MATRIX_BLUE_BIAS_SGI,
        PostColorMatrixBlueScaleSgi = Raw.GL_POST_COLOR_MATRIX_BLUE_SCALE_SGI,
        PostColorMatrixColorTableSgi = Raw.GL_POST_COLOR_MATRIX_COLOR_TABLE_SGI,
        PostColorMatrixGreenBiasSgi = Raw.GL_POST_COLOR_MATRIX_GREEN_BIAS_SGI,
        PostColorMatrixGreenScaleSgi = Raw.GL_POST_COLOR_MATRIX_GREEN_SCALE_SGI,
        PostColorMatrixRedBiasSgi = Raw.GL_POST_COLOR_MATRIX_RED_BIAS_SGI,
        PostColorMatrixRedScaleSgi = Raw.GL_POST_COLOR_MATRIX_RED_SCALE_SGI,
        PostConvolutionAlphaBiasExt = Raw.GL_POST_CONVOLUTION_ALPHA_BIAS_EXT,
        PostConvolutionAlphaScaleExt = Raw.GL_POST_CONVOLUTION_ALPHA_SCALE_EXT,
        PostConvolutionBlueBiasExt = Raw.GL_POST_CONVOLUTION_BLUE_BIAS_EXT,
        PostConvolutionBlueScaleExt = Raw.GL_POST_CONVOLUTION_BLUE_SCALE_EXT,
        PostConvolutionColorTableSgi = Raw.GL_POST_CONVOLUTION_COLOR_TABLE_SGI,
        PostConvolutionGreenBiasExt = Raw.GL_POST_CONVOLUTION_GREEN_BIAS_EXT,
        PostConvolutionGreenScaleExt = Raw.GL_POST_CONVOLUTION_GREEN_SCALE_EXT,
        PostConvolutionRedBiasExt = Raw.GL_POST_CONVOLUTION_RED_BIAS_EXT,
        PostConvolutionRedScaleExt = Raw.GL_POST_CONVOLUTION_RED_SCALE_EXT,
        PostTextureFilterBiasRangeSgix = Raw.GL_POST_TEXTURE_FILTER_BIAS_RANGE_SGIX,
        PostTextureFilterScaleRangeSgix = Raw.GL_POST_TEXTURE_FILTER_SCALE_RANGE_SGIX,
        ProjectionMatrix = Raw.GL_PROJECTION_MATRIX,
        ProjectionStackDepth = Raw.GL_PROJECTION_STACK_DEPTH,
        ReadBuffer = Raw.GL_READ_BUFFER,
        ReadBufferExt = Raw.GL_READ_BUFFER_EXT,
        ReadBufferNv = Raw.GL_READ_BUFFER_NV,
        RedBias = Raw.GL_RED_BIAS,
        RedBits = Raw.GL_RED_BITS,
        RedScale = Raw.GL_RED_SCALE,
        ReferencePlaneEquationSgix = Raw.GL_REFERENCE_PLANE_EQUATION_SGIX,
        ReferencePlaneSgix = Raw.GL_REFERENCE_PLANE_SGIX,
        RenderMode = Raw.GL_RENDER_MODE,
        RescaleNormalExt = Raw.GL_RESCALE_NORMAL_EXT,
        RgbaMode = Raw.GL_RGBA_MODE,
        SamplesSgis = Raw.GL_SAMPLES_SGIS,
        SampleAlphaToMaskSgis = Raw.GL_SAMPLE_ALPHA_TO_MASK_SGIS,
        SampleAlphaToOneSgis = Raw.GL_SAMPLE_ALPHA_TO_ONE_SGIS,
        SampleBuffersSgis = Raw.GL_SAMPLE_BUFFERS_SGIS,
        SampleMaskInvertSgis = Raw.GL_SAMPLE_MASK_INVERT_SGIS,
        SampleMaskSgis = Raw.GL_SAMPLE_MASK_SGIS,
        SampleMaskValueSgis = Raw.GL_SAMPLE_MASK_VALUE_SGIS,
        SamplePatternSgis = Raw.GL_SAMPLE_PATTERN_SGIS,
        ScissorBox = Raw.GL_SCISSOR_BOX,
        ScissorTest = Raw.GL_SCISSOR_TEST,
        SelectionBufferSize = Raw.GL_SELECTION_BUFFER_SIZE,
        SeparableTwoDExt = Raw.GL_SEPARABLE_2D_EXT,
        ShadeModel = Raw.GL_SHADE_MODEL,
        SharedTexturePaletteExt = Raw.GL_SHARED_TEXTURE_PALETTE_EXT,
        SmoothLineWidthGranularity = Raw.GL_SMOOTH_LINE_WIDTH_GRANULARITY,
        SmoothLineWidthRange = Raw.GL_SMOOTH_LINE_WIDTH_RANGE,
        SmoothPointSizeGranularity = Raw.GL_SMOOTH_POINT_SIZE_GRANULARITY,
        SmoothPointSizeRange = Raw.GL_SMOOTH_POINT_SIZE_RANGE,
        SpriteAxisSgix = Raw.GL_SPRITE_AXIS_SGIX,
        SpriteModeSgix = Raw.GL_SPRITE_MODE_SGIX,
        SpriteSgix = Raw.GL_SPRITE_SGIX,
        SpriteTranslationSgix = Raw.GL_SPRITE_TRANSLATION_SGIX,
        StencilBits = Raw.GL_STENCIL_BITS,
        StencilClearValue = Raw.GL_STENCIL_CLEAR_VALUE,
        StencilFail = Raw.GL_STENCIL_FAIL,
        StencilFunc = Raw.GL_STENCIL_FUNC,
        StencilPassDepthFail = Raw.GL_STENCIL_PASS_DEPTH_FAIL,
        StencilPassDepthPass = Raw.GL_STENCIL_PASS_DEPTH_PASS,
        StencilRef = Raw.GL_STENCIL_REF,
        StencilTest = Raw.GL_STENCIL_TEST,
        StencilValueMask = Raw.GL_STENCIL_VALUE_MASK,
        StencilWritemask = Raw.GL_STENCIL_WRITEMASK,
        Stereo = Raw.GL_STEREO,
        SubpixelBits = Raw.GL_SUBPIXEL_BITS,
        TextureOneD = Raw.GL_TEXTURE_1D,
        TextureTwoD = Raw.GL_TEXTURE_2D,
        TextureThreeDBindingExt = Raw.GL_TEXTURE_3D_BINDING_EXT,
        TextureThreeDExt = Raw.GL_TEXTURE_3D_EXT,
        TextureFourDBindingSgis = Raw.GL_TEXTURE_4D_BINDING_SGIS,
        TextureFourDSgis = Raw.GL_TEXTURE_4D_SGIS,
        TextureBindingOneD = Raw.GL_TEXTURE_BINDING_1D,
        TextureBindingTwoD = Raw.GL_TEXTURE_BINDING_2D,
        TextureBindingThreeD = Raw.GL_TEXTURE_BINDING_3D,
        TextureColorTableSgi = Raw.GL_TEXTURE_COLOR_TABLE_SGI,
        TextureCoordArray = Raw.GL_TEXTURE_COORD_ARRAY,
        TextureCoordArrayCountExt = Raw.GL_TEXTURE_COORD_ARRAY_COUNT_EXT,
        TextureCoordArraySize = Raw.GL_TEXTURE_COORD_ARRAY_SIZE,
        TextureCoordArrayStride = Raw.GL_TEXTURE_COORD_ARRAY_STRIDE,
        TextureCoordArrayType = Raw.GL_TEXTURE_COORD_ARRAY_TYPE,
        TextureGenQ = Raw.GL_TEXTURE_GEN_Q,
        TextureGenR = Raw.GL_TEXTURE_GEN_R,
        TextureGenS = Raw.GL_TEXTURE_GEN_S,
        TextureGenT = Raw.GL_TEXTURE_GEN_T,
        TextureMatrix = Raw.GL_TEXTURE_MATRIX,
        TextureStackDepth = Raw.GL_TEXTURE_STACK_DEPTH,
        UnpackAlignment = Raw.GL_UNPACK_ALIGNMENT,
        UnpackCmykHintExt = Raw.GL_UNPACK_CMYK_HINT_EXT,
        UnpackImageDepthSgis = Raw.GL_UNPACK_IMAGE_DEPTH_SGIS,
        UnpackImageHeightExt = Raw.GL_UNPACK_IMAGE_HEIGHT_EXT,
        UnpackLsbFirst = Raw.GL_UNPACK_LSB_FIRST,
        UnpackResampleSgix = Raw.GL_UNPACK_RESAMPLE_SGIX,
        UnpackRowLength = Raw.GL_UNPACK_ROW_LENGTH,
        UnpackSkipImagesExt = Raw.GL_UNPACK_SKIP_IMAGES_EXT,
        UnpackSkipPixels = Raw.GL_UNPACK_SKIP_PIXELS,
        UnpackSkipRows = Raw.GL_UNPACK_SKIP_ROWS,
        UnpackSkipVolumesSgis = Raw.GL_UNPACK_SKIP_VOLUMES_SGIS,
        UnpackSubsampleRateSgix = Raw.GL_UNPACK_SUBSAMPLE_RATE_SGIX,
        UnpackSwapBytes = Raw.GL_UNPACK_SWAP_BYTES,
        VertexArray = Raw.GL_VERTEX_ARRAY,
        VertexArrayCountExt = Raw.GL_VERTEX_ARRAY_COUNT_EXT,
        VertexArraySize = Raw.GL_VERTEX_ARRAY_SIZE,
        VertexArrayStride = Raw.GL_VERTEX_ARRAY_STRIDE,
        VertexArrayType = Raw.GL_VERTEX_ARRAY_TYPE,
        VertexPreclipHintSgix = Raw.GL_VERTEX_PRECLIP_HINT_SGIX,
        VertexPreclipSgix = Raw.GL_VERTEX_PRECLIP_SGIX,
        Viewport = Raw.GL_VIEWPORT,
        ZoomX = Raw.GL_ZOOM_X,
        ZoomY = Raw.GL_ZOOM_Y,
    }
    public enum GetPointervPName : uint
    {
        ColorArrayPointer = Raw.GL_COLOR_ARRAY_POINTER,
        ColorArrayPointerExt = Raw.GL_COLOR_ARRAY_POINTER_EXT,
        EdgeFlagArrayPointer = Raw.GL_EDGE_FLAG_ARRAY_POINTER,
        EdgeFlagArrayPointerExt = Raw.GL_EDGE_FLAG_ARRAY_POINTER_EXT,
        FeedbackBufferPointer = Raw.GL_FEEDBACK_BUFFER_POINTER,
        IndexArrayPointer = Raw.GL_INDEX_ARRAY_POINTER,
        IndexArrayPointerExt = Raw.GL_INDEX_ARRAY_POINTER_EXT,
        InstrumentBufferPointerSgix = Raw.GL_INSTRUMENT_BUFFER_POINTER_SGIX,
        NormalArrayPointer = Raw.GL_NORMAL_ARRAY_POINTER,
        NormalArrayPointerExt = Raw.GL_NORMAL_ARRAY_POINTER_EXT,
        SelectionBufferPointer = Raw.GL_SELECTION_BUFFER_POINTER,
        TextureCoordArrayPointer = Raw.GL_TEXTURE_COORD_ARRAY_POINTER,
        TextureCoordArrayPointerExt = Raw.GL_TEXTURE_COORD_ARRAY_POINTER_EXT,
        VertexArrayPointer = Raw.GL_VERTEX_ARRAY_POINTER,
        VertexArrayPointerExt = Raw.GL_VERTEX_ARRAY_POINTER_EXT,
    }
    public enum GetTextureParameter : uint
    {
        DetailTextureFuncPointsSgis = Raw.GL_DETAIL_TEXTURE_FUNC_POINTS_SGIS,
        DetailTextureLevelSgis = Raw.GL_DETAIL_TEXTURE_LEVEL_SGIS,
        DetailTextureModeSgis = Raw.GL_DETAIL_TEXTURE_MODE_SGIS,
        DualTextureSelectSgis = Raw.GL_DUAL_TEXTURE_SELECT_SGIS,
        GenerateMipmapSgis = Raw.GL_GENERATE_MIPMAP_SGIS,
        PostTextureFilterBiasSgix = Raw.GL_POST_TEXTURE_FILTER_BIAS_SGIX,
        PostTextureFilterScaleSgix = Raw.GL_POST_TEXTURE_FILTER_SCALE_SGIX,
        QuadTextureSelectSgis = Raw.GL_QUAD_TEXTURE_SELECT_SGIS,
        ShadowAmbientSgix = Raw.GL_SHADOW_AMBIENT_SGIX,
        SharpenTextureFuncPointsSgis = Raw.GL_SHARPEN_TEXTURE_FUNC_POINTS_SGIS,
        TextureFourDsizeSgis = Raw.GL_TEXTURE_4DSIZE_SGIS,
        TextureAlphaSize = Raw.GL_TEXTURE_ALPHA_SIZE,
        TextureBaseLevelSgis = Raw.GL_TEXTURE_BASE_LEVEL_SGIS,
        TextureBlueSize = Raw.GL_TEXTURE_BLUE_SIZE,
        TextureBorder = Raw.GL_TEXTURE_BORDER,
        TextureBorderColor = Raw.GL_TEXTURE_BORDER_COLOR,
        TextureBorderColorNv = Raw.GL_TEXTURE_BORDER_COLOR_NV,
        TextureClipmapCenterSgix = Raw.GL_TEXTURE_CLIPMAP_CENTER_SGIX,
        TextureClipmapDepthSgix = Raw.GL_TEXTURE_CLIPMAP_DEPTH_SGIX,
        TextureClipmapFrameSgix = Raw.GL_TEXTURE_CLIPMAP_FRAME_SGIX,
        TextureClipmapLodOffsetSgix = Raw.GL_TEXTURE_CLIPMAP_LOD_OFFSET_SGIX,
        TextureClipmapOffsetSgix = Raw.GL_TEXTURE_CLIPMAP_OFFSET_SGIX,
        TextureClipmapVirtualDepthSgix = Raw.GL_TEXTURE_CLIPMAP_VIRTUAL_DEPTH_SGIX,
        TextureCompareOperatorSgix = Raw.GL_TEXTURE_COMPARE_OPERATOR_SGIX,
        TextureCompareSgix = Raw.GL_TEXTURE_COMPARE_SGIX,
        TextureComponents = Raw.GL_TEXTURE_COMPONENTS,
        TextureDepthExt = Raw.GL_TEXTURE_DEPTH_EXT,
        TextureFilterFourSizeSgis = Raw.GL_TEXTURE_FILTER4_SIZE_SGIS,
        TextureGequalRSgix = Raw.GL_TEXTURE_GEQUAL_R_SGIX,
        TextureGreenSize = Raw.GL_TEXTURE_GREEN_SIZE,
        TextureHeight = Raw.GL_TEXTURE_HEIGHT,
        TextureIntensitySize = Raw.GL_TEXTURE_INTENSITY_SIZE,
        TextureInternalFormat = Raw.GL_TEXTURE_INTERNAL_FORMAT,
        TextureLequalRSgix = Raw.GL_TEXTURE_LEQUAL_R_SGIX,
        TextureLodBiasRSgix = Raw.GL_TEXTURE_LOD_BIAS_R_SGIX,
        TextureLodBiasSSgix = Raw.GL_TEXTURE_LOD_BIAS_S_SGIX,
        TextureLodBiasTSgix = Raw.GL_TEXTURE_LOD_BIAS_T_SGIX,
        TextureLuminanceSize = Raw.GL_TEXTURE_LUMINANCE_SIZE,
        TextureMagFilter = Raw.GL_TEXTURE_MAG_FILTER,
        TextureMaxClampRSgix = Raw.GL_TEXTURE_MAX_CLAMP_R_SGIX,
        TextureMaxClampSSgix = Raw.GL_TEXTURE_MAX_CLAMP_S_SGIX,
        TextureMaxClampTSgix = Raw.GL_TEXTURE_MAX_CLAMP_T_SGIX,
        TextureMaxLevelSgis = Raw.GL_TEXTURE_MAX_LEVEL_SGIS,
        TextureMaxLodSgis = Raw.GL_TEXTURE_MAX_LOD_SGIS,
        TextureMinFilter = Raw.GL_TEXTURE_MIN_FILTER,
        TextureMinLodSgis = Raw.GL_TEXTURE_MIN_LOD_SGIS,
        TexturePriority = Raw.GL_TEXTURE_PRIORITY,
        TextureRedSize = Raw.GL_TEXTURE_RED_SIZE,
        TextureResident = Raw.GL_TEXTURE_RESIDENT,
        TextureWidth = Raw.GL_TEXTURE_WIDTH,
        TextureWrapQSgis = Raw.GL_TEXTURE_WRAP_Q_SGIS,
        TextureWrapRExt = Raw.GL_TEXTURE_WRAP_R_EXT,
        TextureWrapS = Raw.GL_TEXTURE_WRAP_S,
        TextureWrapT = Raw.GL_TEXTURE_WRAP_T,
    }
    public enum HintMode : uint
    {
        DontCare = Raw.GL_DONT_CARE,
        Fastest = Raw.GL_FASTEST,
        Nicest = Raw.GL_NICEST,
    }
    public enum HintTarget : uint
    {
        AllowDrawFrgHintPgi = Raw.GL_ALLOW_DRAW_FRG_HINT_PGI,
        AllowDrawMemHintPgi = Raw.GL_ALLOW_DRAW_MEM_HINT_PGI,
        AllowDrawObjHintPgi = Raw.GL_ALLOW_DRAW_OBJ_HINT_PGI,
        AllowDrawWinHintPgi = Raw.GL_ALLOW_DRAW_WIN_HINT_PGI,
        AlwaysFastHintPgi = Raw.GL_ALWAYS_FAST_HINT_PGI,
        AlwaysSoftHintPgi = Raw.GL_ALWAYS_SOFT_HINT_PGI,
        BackNormalsHintPgi = Raw.GL_BACK_NORMALS_HINT_PGI,
        BinningControlHintQcom = Raw.GL_BINNING_CONTROL_HINT_QCOM,
        ClipFarHintPgi = Raw.GL_CLIP_FAR_HINT_PGI,
        ClipNearHintPgi = Raw.GL_CLIP_NEAR_HINT_PGI,
        ClipVolumeClippingHintExt = Raw.GL_CLIP_VOLUME_CLIPPING_HINT_EXT,
        ConserveMemoryHintPgi = Raw.GL_CONSERVE_MEMORY_HINT_PGI,
        ConvolutionHintSgix = Raw.GL_CONVOLUTION_HINT_SGIX,
        FogHint = Raw.GL_FOG_HINT,
        FragmentShaderDerivativeHint = Raw.GL_FRAGMENT_SHADER_DERIVATIVE_HINT,
        FragmentShaderDerivativeHintArb = Raw.GL_FRAGMENT_SHADER_DERIVATIVE_HINT_ARB,
        FragmentShaderDerivativeHintOes = Raw.GL_FRAGMENT_SHADER_DERIVATIVE_HINT_OES,
        FullStippleHintPgi = Raw.GL_FULL_STIPPLE_HINT_PGI,
        GenerateMipmapHint = Raw.GL_GENERATE_MIPMAP_HINT,
        GenerateMipmapHintSgis = Raw.GL_GENERATE_MIPMAP_HINT_SGIS,
        LineQualityHintSgix = Raw.GL_LINE_QUALITY_HINT_SGIX,
        LineSmoothHint = Raw.GL_LINE_SMOOTH_HINT,
        MaterialSideHintPgi = Raw.GL_MATERIAL_SIDE_HINT_PGI,
        MaxVertexHintPgi = Raw.GL_MAX_VERTEX_HINT_PGI,
        MultisampleFilterHintNv = Raw.GL_MULTISAMPLE_FILTER_HINT_NV,
        NativeGraphicsBeginHintPgi = Raw.GL_NATIVE_GRAPHICS_BEGIN_HINT_PGI,
        NativeGraphicsEndHintPgi = Raw.GL_NATIVE_GRAPHICS_END_HINT_PGI,
        PackCmykHintExt = Raw.GL_PACK_CMYK_HINT_EXT,
        PerspectiveCorrectionHint = Raw.GL_PERSPECTIVE_CORRECTION_HINT,
        PhongHintWin = Raw.GL_PHONG_HINT_WIN,
        PointSmoothHint = Raw.GL_POINT_SMOOTH_HINT,
        PolygonSmoothHint = Raw.GL_POLYGON_SMOOTH_HINT,
        PreferDoublebufferHintPgi = Raw.GL_PREFER_DOUBLEBUFFER_HINT_PGI,
        ProgramBinaryRetrievableHint = Raw.GL_PROGRAM_BINARY_RETRIEVABLE_HINT,
        ReclaimMemoryHintPgi = Raw.GL_RECLAIM_MEMORY_HINT_PGI,
        ScalebiasHintSgix = Raw.GL_SCALEBIAS_HINT_SGIX,
        StrictDepthfuncHintPgi = Raw.GL_STRICT_DEPTHFUNC_HINT_PGI,
        StrictLightingHintPgi = Raw.GL_STRICT_LIGHTING_HINT_PGI,
        StrictScissorHintPgi = Raw.GL_STRICT_SCISSOR_HINT_PGI,
        TextureCompressionHint = Raw.GL_TEXTURE_COMPRESSION_HINT,
        TextureCompressionHintArb = Raw.GL_TEXTURE_COMPRESSION_HINT_ARB,
        TextureMultiBufferHintSgix = Raw.GL_TEXTURE_MULTI_BUFFER_HINT_SGIX,
        TextureStorageHintApple = Raw.GL_TEXTURE_STORAGE_HINT_APPLE,
        TransformHintApple = Raw.GL_TRANSFORM_HINT_APPLE,
        UnpackCmykHintExt = Raw.GL_UNPACK_CMYK_HINT_EXT,
        VertexArrayStorageHintApple = Raw.GL_VERTEX_ARRAY_STORAGE_HINT_APPLE,
        VertexConsistentHintPgi = Raw.GL_VERTEX_CONSISTENT_HINT_PGI,
        VertexDataHintPgi = Raw.GL_VERTEX_DATA_HINT_PGI,
        VertexPreclipHintSgix = Raw.GL_VERTEX_PRECLIP_HINT_SGIX,
        VertexPreclipSgix = Raw.GL_VERTEX_PRECLIP_SGIX,
        WideLineHintPgi = Raw.GL_WIDE_LINE_HINT_PGI,
    }
    public enum HistogramTargetEXT : uint
    {
        Histogram = Raw.GL_HISTOGRAM,
        HistogramExt = Raw.GL_HISTOGRAM_EXT,
        ProxyHistogram = Raw.GL_PROXY_HISTOGRAM,
        ProxyHistogramExt = Raw.GL_PROXY_HISTOGRAM_EXT,
    }
    public enum IndexPointerType : uint
    {
        Double = Raw.GL_DOUBLE,
        Float = Raw.GL_FLOAT,
        Int = Raw.GL_INT,
        Short = Raw.GL_SHORT,
    }
    public enum InterleavedArrayFormat : uint
    {
        CThreeFVThreeF = Raw.GL_C3F_V3F,
        CFourFNThreeFVThreeF = Raw.GL_C4F_N3F_V3F,
        CFourUbVTwoF = Raw.GL_C4UB_V2F,
        CFourUbVThreeF = Raw.GL_C4UB_V3F,
        NThreeFVThreeF = Raw.GL_N3F_V3F,
        TTwoFCThreeFVThreeF = Raw.GL_T2F_C3F_V3F,
        TTwoFCFourFNThreeFVThreeF = Raw.GL_T2F_C4F_N3F_V3F,
        TTwoFCFourUbVThreeF = Raw.GL_T2F_C4UB_V3F,
        TTwoFNThreeFVThreeF = Raw.GL_T2F_N3F_V3F,
        TTwoFVThreeF = Raw.GL_T2F_V3F,
        TFourFCFourFNThreeFVFourF = Raw.GL_T4F_C4F_N3F_V4F,
        TFourFVFourF = Raw.GL_T4F_V4F,
        VTwoF = Raw.GL_V2F,
        VThreeF = Raw.GL_V3F,
    }
    public enum LightEnvModeSGIX : uint
    {
        Add = Raw.GL_ADD,
        Modulate = Raw.GL_MODULATE,
        Replace = Raw.GL_REPLACE,
    }
    public enum LightEnvParameterSGIX : uint
    {
        LightEnvModeSgix = Raw.GL_LIGHT_ENV_MODE_SGIX,
    }
    public enum LightModelColorControl : uint
    {
        SeparateSpecularColor = Raw.GL_SEPARATE_SPECULAR_COLOR,
        SeparateSpecularColorExt = Raw.GL_SEPARATE_SPECULAR_COLOR_EXT,
        SingleColor = Raw.GL_SINGLE_COLOR,
        SingleColorExt = Raw.GL_SINGLE_COLOR_EXT,
    }
    public enum LightModelParameter : uint
    {
        LightModelAmbient = Raw.GL_LIGHT_MODEL_AMBIENT,
        LightModelColorControl = Raw.GL_LIGHT_MODEL_COLOR_CONTROL,
        LightModelColorControlExt = Raw.GL_LIGHT_MODEL_COLOR_CONTROL_EXT,
        LightModelLocalViewer = Raw.GL_LIGHT_MODEL_LOCAL_VIEWER,
        LightModelTwoSide = Raw.GL_LIGHT_MODEL_TWO_SIDE,
    }
    public enum LightName : uint
    {
        FragmentLightZeroSgix = Raw.GL_FRAGMENT_LIGHT0_SGIX,
        FragmentLightOneSgix = Raw.GL_FRAGMENT_LIGHT1_SGIX,
        FragmentLightTwoSgix = Raw.GL_FRAGMENT_LIGHT2_SGIX,
        FragmentLightThreeSgix = Raw.GL_FRAGMENT_LIGHT3_SGIX,
        FragmentLightFourSgix = Raw.GL_FRAGMENT_LIGHT4_SGIX,
        FragmentLightFiveSgix = Raw.GL_FRAGMENT_LIGHT5_SGIX,
        FragmentLightSixSgix = Raw.GL_FRAGMENT_LIGHT6_SGIX,
        FragmentLightSevenSgix = Raw.GL_FRAGMENT_LIGHT7_SGIX,
        LightZero = Raw.GL_LIGHT0,
        LightOne = Raw.GL_LIGHT1,
        LightTwo = Raw.GL_LIGHT2,
        LightThree = Raw.GL_LIGHT3,
        LightFour = Raw.GL_LIGHT4,
        LightFive = Raw.GL_LIGHT5,
        LightSix = Raw.GL_LIGHT6,
        LightSeven = Raw.GL_LIGHT7,
    }
    public enum LightParameter : uint
    {
        Ambient = Raw.GL_AMBIENT,
        ConstantAttenuation = Raw.GL_CONSTANT_ATTENUATION,
        Diffuse = Raw.GL_DIFFUSE,
        LinearAttenuation = Raw.GL_LINEAR_ATTENUATION,
        Position = Raw.GL_POSITION,
        QuadraticAttenuation = Raw.GL_QUADRATIC_ATTENUATION,
        Specular = Raw.GL_SPECULAR,
        SpotCutoff = Raw.GL_SPOT_CUTOFF,
        SpotDirection = Raw.GL_SPOT_DIRECTION,
        SpotExponent = Raw.GL_SPOT_EXPONENT,
    }
    public enum ListMode : uint
    {
        Compile = Raw.GL_COMPILE,
        CompileAndExecute = Raw.GL_COMPILE_AND_EXECUTE,
    }
    public enum ListNameType : uint
    {
        TwoBytes = Raw.GL_2_BYTES,
        ThreeBytes = Raw.GL_3_BYTES,
        FourBytes = Raw.GL_4_BYTES,
        Byte = Raw.GL_BYTE,
        Float = Raw.GL_FLOAT,
        Int = Raw.GL_INT,
        Short = Raw.GL_SHORT,
        UnsignedByte = Raw.GL_UNSIGNED_BYTE,
        UnsignedInt = Raw.GL_UNSIGNED_INT,
        UnsignedShort = Raw.GL_UNSIGNED_SHORT,
    }
    public enum ListParameterName : uint
    {
        ListPrioritySgix = Raw.GL_LIST_PRIORITY_SGIX,
    }
    public enum LogicOp : uint
    {
        And = Raw.GL_AND,
        AndInverted = Raw.GL_AND_INVERTED,
        AndReverse = Raw.GL_AND_REVERSE,
        Clear = Raw.GL_CLEAR,
        Copy = Raw.GL_COPY,
        CopyInverted = Raw.GL_COPY_INVERTED,
        Equiv = Raw.GL_EQUIV,
        Invert = Raw.GL_INVERT,
        Nand = Raw.GL_NAND,
        Noop = Raw.GL_NOOP,
        Nor = Raw.GL_NOR,
        Or = Raw.GL_OR,
        OrInverted = Raw.GL_OR_INVERTED,
        OrReverse = Raw.GL_OR_REVERSE,
        Set = Raw.GL_SET,
        Xor = Raw.GL_XOR,
    }
    public enum MapBufferUsageMask : uint
    {
        ClientStorageBit = Raw.GL_CLIENT_STORAGE_BIT,
        DynamicStorageBit = Raw.GL_DYNAMIC_STORAGE_BIT,
        MapCoherentBit = Raw.GL_MAP_COHERENT_BIT,
        MapFlushExplicitBit = Raw.GL_MAP_FLUSH_EXPLICIT_BIT,
        MapFlushExplicitBitExt = Raw.GL_MAP_FLUSH_EXPLICIT_BIT_EXT,
        MapInvalidateBufferBit = Raw.GL_MAP_INVALIDATE_BUFFER_BIT,
        MapInvalidateBufferBitExt = Raw.GL_MAP_INVALIDATE_BUFFER_BIT_EXT,
        MapInvalidateRangeBit = Raw.GL_MAP_INVALIDATE_RANGE_BIT,
        MapInvalidateRangeBitExt = Raw.GL_MAP_INVALIDATE_RANGE_BIT_EXT,
        MapPersistentBit = Raw.GL_MAP_PERSISTENT_BIT,
        MapReadBit = Raw.GL_MAP_READ_BIT,
        MapReadBitExt = Raw.GL_MAP_READ_BIT_EXT,
        MapUnsynchronizedBit = Raw.GL_MAP_UNSYNCHRONIZED_BIT,
        MapUnsynchronizedBitExt = Raw.GL_MAP_UNSYNCHRONIZED_BIT_EXT,
        MapWriteBit = Raw.GL_MAP_WRITE_BIT,
        MapWriteBitExt = Raw.GL_MAP_WRITE_BIT_EXT,
    }
    public enum MapTarget : uint
    {
        GeometryDeformationSgix = Raw.GL_GEOMETRY_DEFORMATION_SGIX,
        MapOneColorFour = Raw.GL_MAP1_COLOR_4,
        MapOneIndex = Raw.GL_MAP1_INDEX,
        MapOneNormal = Raw.GL_MAP1_NORMAL,
        MapOneTextureCoordOne = Raw.GL_MAP1_TEXTURE_COORD_1,
        MapOneTextureCoordTwo = Raw.GL_MAP1_TEXTURE_COORD_2,
        MapOneTextureCoordThree = Raw.GL_MAP1_TEXTURE_COORD_3,
        MapOneTextureCoordFour = Raw.GL_MAP1_TEXTURE_COORD_4,
        MapOneVertexThree = Raw.GL_MAP1_VERTEX_3,
        MapOneVertexFour = Raw.GL_MAP1_VERTEX_4,
        MapTwoColorFour = Raw.GL_MAP2_COLOR_4,
        MapTwoIndex = Raw.GL_MAP2_INDEX,
        MapTwoNormal = Raw.GL_MAP2_NORMAL,
        MapTwoTextureCoordOne = Raw.GL_MAP2_TEXTURE_COORD_1,
        MapTwoTextureCoordTwo = Raw.GL_MAP2_TEXTURE_COORD_2,
        MapTwoTextureCoordThree = Raw.GL_MAP2_TEXTURE_COORD_3,
        MapTwoTextureCoordFour = Raw.GL_MAP2_TEXTURE_COORD_4,
        MapTwoVertexThree = Raw.GL_MAP2_VERTEX_3,
        MapTwoVertexFour = Raw.GL_MAP2_VERTEX_4,
        TextureDeformationSgix = Raw.GL_TEXTURE_DEFORMATION_SGIX,
    }
    public enum MapTextureFormatINTEL : uint
    {
        LayoutDefaultIntel = Raw.GL_LAYOUT_DEFAULT_INTEL,
        LayoutLinearCpuCachedIntel = Raw.GL_LAYOUT_LINEAR_CPU_CACHED_INTEL,
        LayoutLinearIntel = Raw.GL_LAYOUT_LINEAR_INTEL,
    }
    public enum MaterialFace : uint
    {
        Back = Raw.GL_BACK,
        Front = Raw.GL_FRONT,
        FrontAndBack = Raw.GL_FRONT_AND_BACK,
    }
    public enum MaterialParameter : uint
    {
        Ambient = Raw.GL_AMBIENT,
        AmbientAndDiffuse = Raw.GL_AMBIENT_AND_DIFFUSE,
        ColorIndexes = Raw.GL_COLOR_INDEXES,
        Diffuse = Raw.GL_DIFFUSE,
        Emission = Raw.GL_EMISSION,
        Shininess = Raw.GL_SHININESS,
        Specular = Raw.GL_SPECULAR,
    }
    public enum MatrixMode : uint
    {
        Modelview = Raw.GL_MODELVIEW,
        ModelviewZeroExt = Raw.GL_MODELVIEW0_EXT,
        Projection = Raw.GL_PROJECTION,
        Texture = Raw.GL_TEXTURE,
    }
    public enum MemoryBarrierMask : uint
    {
        AllBarrierBits = Raw.GL_ALL_BARRIER_BITS,
        AllBarrierBitsExt = Raw.GL_ALL_BARRIER_BITS_EXT,
        AtomicCounterBarrierBit = Raw.GL_ATOMIC_COUNTER_BARRIER_BIT,
        AtomicCounterBarrierBitExt = Raw.GL_ATOMIC_COUNTER_BARRIER_BIT_EXT,
        BufferUpdateBarrierBit = Raw.GL_BUFFER_UPDATE_BARRIER_BIT,
        BufferUpdateBarrierBitExt = Raw.GL_BUFFER_UPDATE_BARRIER_BIT_EXT,
        ClientMappedBufferBarrierBit = Raw.GL_CLIENT_MAPPED_BUFFER_BARRIER_BIT,
        CommandBarrierBit = Raw.GL_COMMAND_BARRIER_BIT,
        CommandBarrierBitExt = Raw.GL_COMMAND_BARRIER_BIT_EXT,
        ElementArrayBarrierBit = Raw.GL_ELEMENT_ARRAY_BARRIER_BIT,
        ElementArrayBarrierBitExt = Raw.GL_ELEMENT_ARRAY_BARRIER_BIT_EXT,
        FramebufferBarrierBit = Raw.GL_FRAMEBUFFER_BARRIER_BIT,
        FramebufferBarrierBitExt = Raw.GL_FRAMEBUFFER_BARRIER_BIT_EXT,
        PixelBufferBarrierBit = Raw.GL_PIXEL_BUFFER_BARRIER_BIT,
        PixelBufferBarrierBitExt = Raw.GL_PIXEL_BUFFER_BARRIER_BIT_EXT,
        QueryBufferBarrierBit = Raw.GL_QUERY_BUFFER_BARRIER_BIT,
        ShaderGlobalAccessBarrierBitNv = Raw.GL_SHADER_GLOBAL_ACCESS_BARRIER_BIT_NV,
        ShaderImageAccessBarrierBit = Raw.GL_SHADER_IMAGE_ACCESS_BARRIER_BIT,
        ShaderImageAccessBarrierBitExt = Raw.GL_SHADER_IMAGE_ACCESS_BARRIER_BIT_EXT,
        ShaderStorageBarrierBit = Raw.GL_SHADER_STORAGE_BARRIER_BIT,
        TextureFetchBarrierBit = Raw.GL_TEXTURE_FETCH_BARRIER_BIT,
        TextureFetchBarrierBitExt = Raw.GL_TEXTURE_FETCH_BARRIER_BIT_EXT,
        TextureUpdateBarrierBit = Raw.GL_TEXTURE_UPDATE_BARRIER_BIT,
        TextureUpdateBarrierBitExt = Raw.GL_TEXTURE_UPDATE_BARRIER_BIT_EXT,
        TransformFeedbackBarrierBit = Raw.GL_TRANSFORM_FEEDBACK_BARRIER_BIT,
        TransformFeedbackBarrierBitExt = Raw.GL_TRANSFORM_FEEDBACK_BARRIER_BIT_EXT,
        UniformBarrierBit = Raw.GL_UNIFORM_BARRIER_BIT,
        UniformBarrierBitExt = Raw.GL_UNIFORM_BARRIER_BIT_EXT,
        VertexAttribArrayBarrierBit = Raw.GL_VERTEX_ATTRIB_ARRAY_BARRIER_BIT,
        VertexAttribArrayBarrierBitExt = Raw.GL_VERTEX_ATTRIB_ARRAY_BARRIER_BIT_EXT,
    }
    public enum MeshMode1 : uint
    {
        Line = Raw.GL_LINE,
        Point = Raw.GL_POINT,
    }
    public enum MeshMode2 : uint
    {
        Fill = Raw.GL_FILL,
        Line = Raw.GL_LINE,
        Point = Raw.GL_POINT,
    }
    public enum MinmaxTargetEXT : uint
    {
        Minmax = Raw.GL_MINMAX,
        MinmaxExt = Raw.GL_MINMAX_EXT,
    }
    public enum NormalPointerType : uint
    {
        Byte = Raw.GL_BYTE,
        Double = Raw.GL_DOUBLE,
        Float = Raw.GL_FLOAT,
        Int = Raw.GL_INT,
        Short = Raw.GL_SHORT,
    }
    public enum PixelCopyType : uint
    {
        Color = Raw.GL_COLOR,
        ColorExt = Raw.GL_COLOR_EXT,
        Depth = Raw.GL_DEPTH,
        DepthExt = Raw.GL_DEPTH_EXT,
        Stencil = Raw.GL_STENCIL,
        StencilExt = Raw.GL_STENCIL_EXT,
    }
    public enum PixelFormat : uint
    {
        AbgrExt = Raw.GL_ABGR_EXT,
        Alpha = Raw.GL_ALPHA,
        Blue = Raw.GL_BLUE,
        CmykaExt = Raw.GL_CMYKA_EXT,
        CmykExt = Raw.GL_CMYK_EXT,
        ColorIndex = Raw.GL_COLOR_INDEX,
        DepthComponent = Raw.GL_DEPTH_COMPONENT,
        Green = Raw.GL_GREEN,
        Luminance = Raw.GL_LUMINANCE,
        LuminanceAlpha = Raw.GL_LUMINANCE_ALPHA,
        Red = Raw.GL_RED,
        RedExt = Raw.GL_RED_EXT,
        Rgb = Raw.GL_RGB,
        Rgba = Raw.GL_RGBA,
        StencilIndex = Raw.GL_STENCIL_INDEX,
        UnsignedInt = Raw.GL_UNSIGNED_INT,
        UnsignedShort = Raw.GL_UNSIGNED_SHORT,
        YcrcbFourTwoTwoSgix = Raw.GL_YCRCB_422_SGIX,
        YcrcbFourFourFourSgix = Raw.GL_YCRCB_444_SGIX,
    }
    public enum InternalFormat : uint
    {
        AlphaOneTwo = Raw.GL_ALPHA12,
        AlphaOneSix = Raw.GL_ALPHA16,
        AlphaOneSixIccSgix = Raw.GL_ALPHA16_ICC_SGIX,
        AlphaFour = Raw.GL_ALPHA4,
        AlphaEight = Raw.GL_ALPHA8,
        AlphaIccSgix = Raw.GL_ALPHA_ICC_SGIX,
        DepthComponentOneSixSgix = Raw.GL_DEPTH_COMPONENT16_SGIX,
        DepthComponentTwoFourSgix = Raw.GL_DEPTH_COMPONENT24_SGIX,
        DepthComponentThreeTwoSgix = Raw.GL_DEPTH_COMPONENT32_SGIX,
        DualAlphaOneTwoSgis = Raw.GL_DUAL_ALPHA12_SGIS,
        DualAlphaOneSixSgis = Raw.GL_DUAL_ALPHA16_SGIS,
        DualAlphaFourSgis = Raw.GL_DUAL_ALPHA4_SGIS,
        DualAlphaEightSgis = Raw.GL_DUAL_ALPHA8_SGIS,
        DualIntensityOneTwoSgis = Raw.GL_DUAL_INTENSITY12_SGIS,
        DualIntensityOneSixSgis = Raw.GL_DUAL_INTENSITY16_SGIS,
        DualIntensityFourSgis = Raw.GL_DUAL_INTENSITY4_SGIS,
        DualIntensityEightSgis = Raw.GL_DUAL_INTENSITY8_SGIS,
        DualLuminanceOneTwoSgis = Raw.GL_DUAL_LUMINANCE12_SGIS,
        DualLuminanceOneSixSgis = Raw.GL_DUAL_LUMINANCE16_SGIS,
        DualLuminanceFourSgis = Raw.GL_DUAL_LUMINANCE4_SGIS,
        DualLuminanceEightSgis = Raw.GL_DUAL_LUMINANCE8_SGIS,
        DualLuminanceAlphaFourSgis = Raw.GL_DUAL_LUMINANCE_ALPHA4_SGIS,
        DualLuminanceAlphaEightSgis = Raw.GL_DUAL_LUMINANCE_ALPHA8_SGIS,
        Intensity = Raw.GL_INTENSITY,
        IntensityOneTwo = Raw.GL_INTENSITY12,
        IntensityOneSix = Raw.GL_INTENSITY16,
        IntensityOneSixIccSgix = Raw.GL_INTENSITY16_ICC_SGIX,
        IntensityFour = Raw.GL_INTENSITY4,
        IntensityEight = Raw.GL_INTENSITY8,
        IntensityIccSgix = Raw.GL_INTENSITY_ICC_SGIX,
        LuminanceOneTwo = Raw.GL_LUMINANCE12,
        LuminanceOneTwoAlphaOneTwo = Raw.GL_LUMINANCE12_ALPHA12,
        LuminanceOneTwoAlphaFour = Raw.GL_LUMINANCE12_ALPHA4,
        LuminanceOneSix = Raw.GL_LUMINANCE16,
        LuminanceOneSixAlphaOneSix = Raw.GL_LUMINANCE16_ALPHA16,
        LuminanceOneSixAlphaEightIccSgix = Raw.GL_LUMINANCE16_ALPHA8_ICC_SGIX,
        LuminanceOneSixIccSgix = Raw.GL_LUMINANCE16_ICC_SGIX,
        LuminanceFour = Raw.GL_LUMINANCE4,
        LuminanceFourAlphaFour = Raw.GL_LUMINANCE4_ALPHA4,
        LuminanceSixAlphaTwo = Raw.GL_LUMINANCE6_ALPHA2,
        LuminanceEight = Raw.GL_LUMINANCE8,
        LuminanceEightAlphaEight = Raw.GL_LUMINANCE8_ALPHA8,
        LuminanceAlphaIccSgix = Raw.GL_LUMINANCE_ALPHA_ICC_SGIX,
        LuminanceIccSgix = Raw.GL_LUMINANCE_ICC_SGIX,
        QuadAlphaFourSgis = Raw.GL_QUAD_ALPHA4_SGIS,
        QuadAlphaEightSgis = Raw.GL_QUAD_ALPHA8_SGIS,
        QuadIntensityFourSgis = Raw.GL_QUAD_INTENSITY4_SGIS,
        QuadIntensityEightSgis = Raw.GL_QUAD_INTENSITY8_SGIS,
        QuadLuminanceFourSgis = Raw.GL_QUAD_LUMINANCE4_SGIS,
        QuadLuminanceEightSgis = Raw.GL_QUAD_LUMINANCE8_SGIS,
        RThreeGThreeBTwo = Raw.GL_R3_G3_B2,
        RFiveGSixBFiveAEightIccSgix = Raw.GL_R5_G6_B5_A8_ICC_SGIX,
        RFiveGSixBFiveIccSgix = Raw.GL_R5_G6_B5_ICC_SGIX,
        RgbOneZero = Raw.GL_RGB10,
        RgbOneZeroATwo = Raw.GL_RGB10_A2,
        RgbOneTwo = Raw.GL_RGB12,
        RgbOneSix = Raw.GL_RGB16,
        RgbTwoExt = Raw.GL_RGB2_EXT,
        RgbFour = Raw.GL_RGB4,
        RgbFive = Raw.GL_RGB5,
        RgbFiveAOne = Raw.GL_RGB5_A1,
        RgbEight = Raw.GL_RGB8,
        RgbaOneTwo = Raw.GL_RGBA12,
        RgbaOneSix = Raw.GL_RGBA16,
        RgbaTwo = Raw.GL_RGBA2,
        RgbaFour = Raw.GL_RGBA4,
        RgbaEight = Raw.GL_RGBA8,
        RgbaIccSgix = Raw.GL_RGBA_ICC_SGIX,
        RgbIccSgix = Raw.GL_RGB_ICC_SGIX,
    }
    public enum PixelMap : uint
    {
        PixelMapAToA = Raw.GL_PIXEL_MAP_A_TO_A,
        PixelMapBToB = Raw.GL_PIXEL_MAP_B_TO_B,
        PixelMapGToG = Raw.GL_PIXEL_MAP_G_TO_G,
        PixelMapIToA = Raw.GL_PIXEL_MAP_I_TO_A,
        PixelMapIToB = Raw.GL_PIXEL_MAP_I_TO_B,
        PixelMapIToG = Raw.GL_PIXEL_MAP_I_TO_G,
        PixelMapIToI = Raw.GL_PIXEL_MAP_I_TO_I,
        PixelMapIToR = Raw.GL_PIXEL_MAP_I_TO_R,
        PixelMapRToR = Raw.GL_PIXEL_MAP_R_TO_R,
        PixelMapSToS = Raw.GL_PIXEL_MAP_S_TO_S,
    }
    public enum PixelStoreParameter : uint
    {
        PackAlignment = Raw.GL_PACK_ALIGNMENT,
        PackImageDepthSgis = Raw.GL_PACK_IMAGE_DEPTH_SGIS,
        PackImageHeight = Raw.GL_PACK_IMAGE_HEIGHT,
        PackImageHeightExt = Raw.GL_PACK_IMAGE_HEIGHT_EXT,
        PackLsbFirst = Raw.GL_PACK_LSB_FIRST,
        PackResampleOml = Raw.GL_PACK_RESAMPLE_OML,
        PackResampleSgix = Raw.GL_PACK_RESAMPLE_SGIX,
        PackRowLength = Raw.GL_PACK_ROW_LENGTH,
        PackSkipImages = Raw.GL_PACK_SKIP_IMAGES,
        PackSkipImagesExt = Raw.GL_PACK_SKIP_IMAGES_EXT,
        PackSkipPixels = Raw.GL_PACK_SKIP_PIXELS,
        PackSkipRows = Raw.GL_PACK_SKIP_ROWS,
        PackSkipVolumesSgis = Raw.GL_PACK_SKIP_VOLUMES_SGIS,
        PackSubsampleRateSgix = Raw.GL_PACK_SUBSAMPLE_RATE_SGIX,
        PackSwapBytes = Raw.GL_PACK_SWAP_BYTES,
        PixelTileCacheSizeSgix = Raw.GL_PIXEL_TILE_CACHE_SIZE_SGIX,
        PixelTileGridDepthSgix = Raw.GL_PIXEL_TILE_GRID_DEPTH_SGIX,
        PixelTileGridHeightSgix = Raw.GL_PIXEL_TILE_GRID_HEIGHT_SGIX,
        PixelTileGridWidthSgix = Raw.GL_PIXEL_TILE_GRID_WIDTH_SGIX,
        PixelTileHeightSgix = Raw.GL_PIXEL_TILE_HEIGHT_SGIX,
        PixelTileWidthSgix = Raw.GL_PIXEL_TILE_WIDTH_SGIX,
        UnpackAlignment = Raw.GL_UNPACK_ALIGNMENT,
        UnpackImageDepthSgis = Raw.GL_UNPACK_IMAGE_DEPTH_SGIS,
        UnpackImageHeight = Raw.GL_UNPACK_IMAGE_HEIGHT,
        UnpackImageHeightExt = Raw.GL_UNPACK_IMAGE_HEIGHT_EXT,
        UnpackLsbFirst = Raw.GL_UNPACK_LSB_FIRST,
        UnpackResampleOml = Raw.GL_UNPACK_RESAMPLE_OML,
        UnpackResampleSgix = Raw.GL_UNPACK_RESAMPLE_SGIX,
        UnpackRowLength = Raw.GL_UNPACK_ROW_LENGTH,
        UnpackRowLengthExt = Raw.GL_UNPACK_ROW_LENGTH_EXT,
        UnpackSkipImages = Raw.GL_UNPACK_SKIP_IMAGES,
        UnpackSkipImagesExt = Raw.GL_UNPACK_SKIP_IMAGES_EXT,
        UnpackSkipPixels = Raw.GL_UNPACK_SKIP_PIXELS,
        UnpackSkipPixelsExt = Raw.GL_UNPACK_SKIP_PIXELS_EXT,
        UnpackSkipRows = Raw.GL_UNPACK_SKIP_ROWS,
        UnpackSkipRowsExt = Raw.GL_UNPACK_SKIP_ROWS_EXT,
        UnpackSkipVolumesSgis = Raw.GL_UNPACK_SKIP_VOLUMES_SGIS,
        UnpackSubsampleRateSgix = Raw.GL_UNPACK_SUBSAMPLE_RATE_SGIX,
        UnpackSwapBytes = Raw.GL_UNPACK_SWAP_BYTES,
    }
    public enum PixelStoreResampleMode : uint
    {
        ResampleDecimateSgix = Raw.GL_RESAMPLE_DECIMATE_SGIX,
        ResampleReplicateSgix = Raw.GL_RESAMPLE_REPLICATE_SGIX,
        ResampleZeroFillSgix = Raw.GL_RESAMPLE_ZERO_FILL_SGIX,
    }
    public enum PixelStoreSubsampleRate : uint
    {
        PixelSubsampleTwoFourTwoFourSgix = Raw.GL_PIXEL_SUBSAMPLE_2424_SGIX,
        PixelSubsampleFourTwoFourTwoSgix = Raw.GL_PIXEL_SUBSAMPLE_4242_SGIX,
        PixelSubsampleFourFourFourFourSgix = Raw.GL_PIXEL_SUBSAMPLE_4444_SGIX,
    }
    public enum PixelTexGenMode : uint
    {
        Luminance = Raw.GL_LUMINANCE,
        LuminanceAlpha = Raw.GL_LUMINANCE_ALPHA,
        None = Raw.GL_NONE,
        PixelTexGenAlphaLsSgix = Raw.GL_PIXEL_TEX_GEN_ALPHA_LS_SGIX,
        PixelTexGenAlphaMsSgix = Raw.GL_PIXEL_TEX_GEN_ALPHA_MS_SGIX,
        PixelTexGenAlphaNoReplaceSgix = Raw.GL_PIXEL_TEX_GEN_ALPHA_NO_REPLACE_SGIX,
        PixelTexGenAlphaReplaceSgix = Raw.GL_PIXEL_TEX_GEN_ALPHA_REPLACE_SGIX,
        Rgb = Raw.GL_RGB,
        Rgba = Raw.GL_RGBA,
    }
    public enum PixelTexGenParameterNameSGIS : uint
    {
        PixelFragmentAlphaSourceSgis = Raw.GL_PIXEL_FRAGMENT_ALPHA_SOURCE_SGIS,
        PixelFragmentRgbSourceSgis = Raw.GL_PIXEL_FRAGMENT_RGB_SOURCE_SGIS,
    }
    public enum PixelTransferParameter : uint
    {
        AlphaBias = Raw.GL_ALPHA_BIAS,
        AlphaScale = Raw.GL_ALPHA_SCALE,
        BlueBias = Raw.GL_BLUE_BIAS,
        BlueScale = Raw.GL_BLUE_SCALE,
        DepthBias = Raw.GL_DEPTH_BIAS,
        DepthScale = Raw.GL_DEPTH_SCALE,
        GreenBias = Raw.GL_GREEN_BIAS,
        GreenScale = Raw.GL_GREEN_SCALE,
        IndexOffset = Raw.GL_INDEX_OFFSET,
        IndexShift = Raw.GL_INDEX_SHIFT,
        MapColor = Raw.GL_MAP_COLOR,
        MapStencil = Raw.GL_MAP_STENCIL,
        PostColorMatrixAlphaBias = Raw.GL_POST_COLOR_MATRIX_ALPHA_BIAS,
        PostColorMatrixAlphaBiasSgi = Raw.GL_POST_COLOR_MATRIX_ALPHA_BIAS_SGI,
        PostColorMatrixAlphaScale = Raw.GL_POST_COLOR_MATRIX_ALPHA_SCALE,
        PostColorMatrixAlphaScaleSgi = Raw.GL_POST_COLOR_MATRIX_ALPHA_SCALE_SGI,
        PostColorMatrixBlueBias = Raw.GL_POST_COLOR_MATRIX_BLUE_BIAS,
        PostColorMatrixBlueBiasSgi = Raw.GL_POST_COLOR_MATRIX_BLUE_BIAS_SGI,
        PostColorMatrixBlueScale = Raw.GL_POST_COLOR_MATRIX_BLUE_SCALE,
        PostColorMatrixBlueScaleSgi = Raw.GL_POST_COLOR_MATRIX_BLUE_SCALE_SGI,
        PostColorMatrixGreenBias = Raw.GL_POST_COLOR_MATRIX_GREEN_BIAS,
        PostColorMatrixGreenBiasSgi = Raw.GL_POST_COLOR_MATRIX_GREEN_BIAS_SGI,
        PostColorMatrixGreenScale = Raw.GL_POST_COLOR_MATRIX_GREEN_SCALE,
        PostColorMatrixGreenScaleSgi = Raw.GL_POST_COLOR_MATRIX_GREEN_SCALE_SGI,
        PostColorMatrixRedBias = Raw.GL_POST_COLOR_MATRIX_RED_BIAS,
        PostColorMatrixRedBiasSgi = Raw.GL_POST_COLOR_MATRIX_RED_BIAS_SGI,
        PostColorMatrixRedScale = Raw.GL_POST_COLOR_MATRIX_RED_SCALE,
        PostColorMatrixRedScaleSgi = Raw.GL_POST_COLOR_MATRIX_RED_SCALE_SGI,
        PostConvolutionAlphaBias = Raw.GL_POST_CONVOLUTION_ALPHA_BIAS,
        PostConvolutionAlphaBiasExt = Raw.GL_POST_CONVOLUTION_ALPHA_BIAS_EXT,
        PostConvolutionAlphaScale = Raw.GL_POST_CONVOLUTION_ALPHA_SCALE,
        PostConvolutionAlphaScaleExt = Raw.GL_POST_CONVOLUTION_ALPHA_SCALE_EXT,
        PostConvolutionBlueBias = Raw.GL_POST_CONVOLUTION_BLUE_BIAS,
        PostConvolutionBlueBiasExt = Raw.GL_POST_CONVOLUTION_BLUE_BIAS_EXT,
        PostConvolutionBlueScale = Raw.GL_POST_CONVOLUTION_BLUE_SCALE,
        PostConvolutionBlueScaleExt = Raw.GL_POST_CONVOLUTION_BLUE_SCALE_EXT,
        PostConvolutionGreenBias = Raw.GL_POST_CONVOLUTION_GREEN_BIAS,
        PostConvolutionGreenBiasExt = Raw.GL_POST_CONVOLUTION_GREEN_BIAS_EXT,
        PostConvolutionGreenScale = Raw.GL_POST_CONVOLUTION_GREEN_SCALE,
        PostConvolutionGreenScaleExt = Raw.GL_POST_CONVOLUTION_GREEN_SCALE_EXT,
        PostConvolutionRedBias = Raw.GL_POST_CONVOLUTION_RED_BIAS,
        PostConvolutionRedBiasExt = Raw.GL_POST_CONVOLUTION_RED_BIAS_EXT,
        PostConvolutionRedScale = Raw.GL_POST_CONVOLUTION_RED_SCALE,
        PostConvolutionRedScaleExt = Raw.GL_POST_CONVOLUTION_RED_SCALE_EXT,
        RedBias = Raw.GL_RED_BIAS,
        RedScale = Raw.GL_RED_SCALE,
    }
    public enum PixelType : uint
    {
        Bitmap = Raw.GL_BITMAP,
        Byte = Raw.GL_BYTE,
        Float = Raw.GL_FLOAT,
        Int = Raw.GL_INT,
        Short = Raw.GL_SHORT,
        UnsignedByte = Raw.GL_UNSIGNED_BYTE,
        UnsignedByteThreeThreeTwo = Raw.GL_UNSIGNED_BYTE_3_3_2,
        UnsignedByteThreeThreeTwoExt = Raw.GL_UNSIGNED_BYTE_3_3_2_EXT,
        UnsignedInt = Raw.GL_UNSIGNED_INT,
        UnsignedIntOneZeroOneZeroOneZeroTwo = Raw.GL_UNSIGNED_INT_10_10_10_2,
        UnsignedIntOneZeroOneZeroOneZeroTwoExt = Raw.GL_UNSIGNED_INT_10_10_10_2_EXT,
        UnsignedIntEightEightEightEight = Raw.GL_UNSIGNED_INT_8_8_8_8,
        UnsignedIntEightEightEightEightExt = Raw.GL_UNSIGNED_INT_8_8_8_8_EXT,
        UnsignedShort = Raw.GL_UNSIGNED_SHORT,
        UnsignedShortFourFourFourFour = Raw.GL_UNSIGNED_SHORT_4_4_4_4,
        UnsignedShortFourFourFourFourExt = Raw.GL_UNSIGNED_SHORT_4_4_4_4_EXT,
        UnsignedShortFiveFiveFiveOne = Raw.GL_UNSIGNED_SHORT_5_5_5_1,
        UnsignedShortFiveFiveFiveOneExt = Raw.GL_UNSIGNED_SHORT_5_5_5_1_EXT,
    }
    public enum PointParameterNameSGIS : uint
    {
        DistanceAttenuationExt = Raw.GL_DISTANCE_ATTENUATION_EXT,
        DistanceAttenuationSgis = Raw.GL_DISTANCE_ATTENUATION_SGIS,
        PointDistanceAttenuation = Raw.GL_POINT_DISTANCE_ATTENUATION,
        PointDistanceAttenuationArb = Raw.GL_POINT_DISTANCE_ATTENUATION_ARB,
        PointFadeThresholdSize = Raw.GL_POINT_FADE_THRESHOLD_SIZE,
        PointFadeThresholdSizeArb = Raw.GL_POINT_FADE_THRESHOLD_SIZE_ARB,
        PointFadeThresholdSizeExt = Raw.GL_POINT_FADE_THRESHOLD_SIZE_EXT,
        PointFadeThresholdSizeSgis = Raw.GL_POINT_FADE_THRESHOLD_SIZE_SGIS,
        PointSizeMax = Raw.GL_POINT_SIZE_MAX,
        PointSizeMaxArb = Raw.GL_POINT_SIZE_MAX_ARB,
        PointSizeMaxExt = Raw.GL_POINT_SIZE_MAX_EXT,
        PointSizeMaxSgis = Raw.GL_POINT_SIZE_MAX_SGIS,
        PointSizeMin = Raw.GL_POINT_SIZE_MIN,
        PointSizeMinArb = Raw.GL_POINT_SIZE_MIN_ARB,
        PointSizeMinExt = Raw.GL_POINT_SIZE_MIN_EXT,
        PointSizeMinSgis = Raw.GL_POINT_SIZE_MIN_SGIS,
    }
    public enum PolygonMode : uint
    {
        Fill = Raw.GL_FILL,
        Line = Raw.GL_LINE,
        Point = Raw.GL_POINT,
    }
    public enum PrimitiveType : uint
    {
        Lines = Raw.GL_LINES,
        LinesAdjacency = Raw.GL_LINES_ADJACENCY,
        LinesAdjacencyArb = Raw.GL_LINES_ADJACENCY_ARB,
        LinesAdjacencyExt = Raw.GL_LINES_ADJACENCY_EXT,
        LineLoop = Raw.GL_LINE_LOOP,
        LineStrip = Raw.GL_LINE_STRIP,
        LineStripAdjacency = Raw.GL_LINE_STRIP_ADJACENCY,
        LineStripAdjacencyArb = Raw.GL_LINE_STRIP_ADJACENCY_ARB,
        LineStripAdjacencyExt = Raw.GL_LINE_STRIP_ADJACENCY_EXT,
        Patches = Raw.GL_PATCHES,
        PatchesExt = Raw.GL_PATCHES_EXT,
        Points = Raw.GL_POINTS,
        Polygon = Raw.GL_POLYGON,
        Quads = Raw.GL_QUADS,
        QuadsExt = Raw.GL_QUADS_EXT,
        QuadStrip = Raw.GL_QUAD_STRIP,
        Triangles = Raw.GL_TRIANGLES,
        TrianglesAdjacency = Raw.GL_TRIANGLES_ADJACENCY,
        TrianglesAdjacencyArb = Raw.GL_TRIANGLES_ADJACENCY_ARB,
        TrianglesAdjacencyExt = Raw.GL_TRIANGLES_ADJACENCY_EXT,
        TriangleFan = Raw.GL_TRIANGLE_FAN,
        TriangleStrip = Raw.GL_TRIANGLE_STRIP,
        TriangleStripAdjacency = Raw.GL_TRIANGLE_STRIP_ADJACENCY,
        TriangleStripAdjacencyArb = Raw.GL_TRIANGLE_STRIP_ADJACENCY_ARB,
        TriangleStripAdjacencyExt = Raw.GL_TRIANGLE_STRIP_ADJACENCY_EXT,
    }
    public enum OcclusionQueryEventMaskAMD : uint
    {
        QueryDepthPassEventBitAmd = Raw.GL_QUERY_DEPTH_PASS_EVENT_BIT_AMD,
        QueryDepthFailEventBitAmd = Raw.GL_QUERY_DEPTH_FAIL_EVENT_BIT_AMD,
        QueryStencilFailEventBitAmd = Raw.GL_QUERY_STENCIL_FAIL_EVENT_BIT_AMD,
        QueryDepthBoundsFailEventBitAmd = Raw.GL_QUERY_DEPTH_BOUNDS_FAIL_EVENT_BIT_AMD,
        QueryAllEventBitsAmd = Raw.GL_QUERY_ALL_EVENT_BITS_AMD,
    }
    public enum ReadBufferMode : uint
    {
        AuxZero = Raw.GL_AUX0,
        AuxOne = Raw.GL_AUX1,
        AuxTwo = Raw.GL_AUX2,
        AuxThree = Raw.GL_AUX3,
        Back = Raw.GL_BACK,
        BackLeft = Raw.GL_BACK_LEFT,
        BackRight = Raw.GL_BACK_RIGHT,
        Front = Raw.GL_FRONT,
        FrontLeft = Raw.GL_FRONT_LEFT,
        FrontRight = Raw.GL_FRONT_RIGHT,
        Left = Raw.GL_LEFT,
        Right = Raw.GL_RIGHT,
    }
    public enum RenderingMode : uint
    {
        Feedback = Raw.GL_FEEDBACK,
        Render = Raw.GL_RENDER,
        Select = Raw.GL_SELECT,
    }
    public enum SamplePatternSGIS : uint
    {
        OnePassExt = Raw.GL_1PASS_EXT,
        OnePassSgis = Raw.GL_1PASS_SGIS,
        TwoPassZeroExt = Raw.GL_2PASS_0_EXT,
        TwoPassZeroSgis = Raw.GL_2PASS_0_SGIS,
        TwoPassOneExt = Raw.GL_2PASS_1_EXT,
        TwoPassOneSgis = Raw.GL_2PASS_1_SGIS,
        FourPassZeroExt = Raw.GL_4PASS_0_EXT,
        FourPassZeroSgis = Raw.GL_4PASS_0_SGIS,
        FourPassOneExt = Raw.GL_4PASS_1_EXT,
        FourPassOneSgis = Raw.GL_4PASS_1_SGIS,
        FourPassTwoExt = Raw.GL_4PASS_2_EXT,
        FourPassTwoSgis = Raw.GL_4PASS_2_SGIS,
        FourPassThreeExt = Raw.GL_4PASS_3_EXT,
        FourPassThreeSgis = Raw.GL_4PASS_3_SGIS,
    }
    public enum SeparableTargetEXT : uint
    {
        SeparableTwoD = Raw.GL_SEPARABLE_2D,
        SeparableTwoDExt = Raw.GL_SEPARABLE_2D_EXT,
    }
    public enum ShadingModel : uint
    {
        Flat = Raw.GL_FLAT,
        Smooth = Raw.GL_SMOOTH,
    }
    public enum StencilFunction : uint
    {
        Always = Raw.GL_ALWAYS,
        Equal = Raw.GL_EQUAL,
        Gequal = Raw.GL_GEQUAL,
        Greater = Raw.GL_GREATER,
        Lequal = Raw.GL_LEQUAL,
        Less = Raw.GL_LESS,
        Never = Raw.GL_NEVER,
        Notequal = Raw.GL_NOTEQUAL,
    }
    public enum StencilOp : uint
    {
        Decr = Raw.GL_DECR,
        Incr = Raw.GL_INCR,
        Invert = Raw.GL_INVERT,
        Keep = Raw.GL_KEEP,
        Replace = Raw.GL_REPLACE,
        Zero = Raw.GL_ZERO,
    }
    public enum StringName : uint
    {
        Extensions = Raw.GL_EXTENSIONS,
        Renderer = Raw.GL_RENDERER,
        Vendor = Raw.GL_VENDOR,
        Version = Raw.GL_VERSION,
    }
    public enum TexCoordPointerType : uint
    {
        Double = Raw.GL_DOUBLE,
        Float = Raw.GL_FLOAT,
        Int = Raw.GL_INT,
        Short = Raw.GL_SHORT,
    }
    public enum TextureCoordName : uint
    {
        S = Raw.GL_S,
        T = Raw.GL_T,
        R = Raw.GL_R,
        Q = Raw.GL_Q,
    }
    public enum TextureEnvMode : uint
    {
        Add = Raw.GL_ADD,
        Blend = Raw.GL_BLEND,
        Decal = Raw.GL_DECAL,
        Modulate = Raw.GL_MODULATE,
        ReplaceExt = Raw.GL_REPLACE_EXT,
        TextureEnvBiasSgix = Raw.GL_TEXTURE_ENV_BIAS_SGIX,
    }
    public enum TextureEnvParameter : uint
    {
        TextureEnvColor = Raw.GL_TEXTURE_ENV_COLOR,
        TextureEnvMode = Raw.GL_TEXTURE_ENV_MODE,
    }
    public enum TextureEnvTarget : uint
    {
        TextureEnv = Raw.GL_TEXTURE_ENV,
    }
    public enum TextureFilterFuncSGIS : uint
    {
        FilterFourSgis = Raw.GL_FILTER4_SGIS,
    }
    public enum TextureGenMode : uint
    {
        EyeDistanceToLineSgis = Raw.GL_EYE_DISTANCE_TO_LINE_SGIS,
        EyeDistanceToPointSgis = Raw.GL_EYE_DISTANCE_TO_POINT_SGIS,
        EyeLinear = Raw.GL_EYE_LINEAR,
        ObjectDistanceToLineSgis = Raw.GL_OBJECT_DISTANCE_TO_LINE_SGIS,
        ObjectDistanceToPointSgis = Raw.GL_OBJECT_DISTANCE_TO_POINT_SGIS,
        ObjectLinear = Raw.GL_OBJECT_LINEAR,
        SphereMap = Raw.GL_SPHERE_MAP,
    }
    public enum TextureGenParameter : uint
    {
        EyeLineSgis = Raw.GL_EYE_LINE_SGIS,
        EyePlane = Raw.GL_EYE_PLANE,
        EyePointSgis = Raw.GL_EYE_POINT_SGIS,
        ObjectLineSgis = Raw.GL_OBJECT_LINE_SGIS,
        ObjectPlane = Raw.GL_OBJECT_PLANE,
        ObjectPointSgis = Raw.GL_OBJECT_POINT_SGIS,
        TextureGenMode = Raw.GL_TEXTURE_GEN_MODE,
    }
    public enum TextureMagFilter : uint
    {
        FilterFourSgis = Raw.GL_FILTER4_SGIS,
        Linear = Raw.GL_LINEAR,
        LinearDetailAlphaSgis = Raw.GL_LINEAR_DETAIL_ALPHA_SGIS,
        LinearDetailColorSgis = Raw.GL_LINEAR_DETAIL_COLOR_SGIS,
        LinearDetailSgis = Raw.GL_LINEAR_DETAIL_SGIS,
        LinearSharpenAlphaSgis = Raw.GL_LINEAR_SHARPEN_ALPHA_SGIS,
        LinearSharpenColorSgis = Raw.GL_LINEAR_SHARPEN_COLOR_SGIS,
        LinearSharpenSgis = Raw.GL_LINEAR_SHARPEN_SGIS,
        Nearest = Raw.GL_NEAREST,
        PixelTexGenQCeilingSgix = Raw.GL_PIXEL_TEX_GEN_Q_CEILING_SGIX,
        PixelTexGenQFloorSgix = Raw.GL_PIXEL_TEX_GEN_Q_FLOOR_SGIX,
        PixelTexGenQRoundSgix = Raw.GL_PIXEL_TEX_GEN_Q_ROUND_SGIX,
    }
    public enum TextureMinFilter : uint
    {
        FilterFourSgis = Raw.GL_FILTER4_SGIS,
        Linear = Raw.GL_LINEAR,
        LinearClipmapLinearSgix = Raw.GL_LINEAR_CLIPMAP_LINEAR_SGIX,
        LinearClipmapNearestSgix = Raw.GL_LINEAR_CLIPMAP_NEAREST_SGIX,
        LinearMipmapLinear = Raw.GL_LINEAR_MIPMAP_LINEAR,
        LinearMipmapNearest = Raw.GL_LINEAR_MIPMAP_NEAREST,
        Nearest = Raw.GL_NEAREST,
        NearestClipmapLinearSgix = Raw.GL_NEAREST_CLIPMAP_LINEAR_SGIX,
        NearestClipmapNearestSgix = Raw.GL_NEAREST_CLIPMAP_NEAREST_SGIX,
        NearestMipmapLinear = Raw.GL_NEAREST_MIPMAP_LINEAR,
        NearestMipmapNearest = Raw.GL_NEAREST_MIPMAP_NEAREST,
        PixelTexGenQCeilingSgix = Raw.GL_PIXEL_TEX_GEN_Q_CEILING_SGIX,
        PixelTexGenQFloorSgix = Raw.GL_PIXEL_TEX_GEN_Q_FLOOR_SGIX,
        PixelTexGenQRoundSgix = Raw.GL_PIXEL_TEX_GEN_Q_ROUND_SGIX,
    }
    public enum TextureParameterName : uint
    {
        DetailTextureLevelSgis = Raw.GL_DETAIL_TEXTURE_LEVEL_SGIS,
        DetailTextureModeSgis = Raw.GL_DETAIL_TEXTURE_MODE_SGIS,
        DualTextureSelectSgis = Raw.GL_DUAL_TEXTURE_SELECT_SGIS,
        GenerateMipmap = Raw.GL_GENERATE_MIPMAP,
        GenerateMipmapSgis = Raw.GL_GENERATE_MIPMAP_SGIS,
        PostTextureFilterBiasSgix = Raw.GL_POST_TEXTURE_FILTER_BIAS_SGIX,
        PostTextureFilterScaleSgix = Raw.GL_POST_TEXTURE_FILTER_SCALE_SGIX,
        QuadTextureSelectSgis = Raw.GL_QUAD_TEXTURE_SELECT_SGIS,
        ShadowAmbientSgix = Raw.GL_SHADOW_AMBIENT_SGIX,
        TextureBorderColor = Raw.GL_TEXTURE_BORDER_COLOR,
        TextureClipmapCenterSgix = Raw.GL_TEXTURE_CLIPMAP_CENTER_SGIX,
        TextureClipmapDepthSgix = Raw.GL_TEXTURE_CLIPMAP_DEPTH_SGIX,
        TextureClipmapFrameSgix = Raw.GL_TEXTURE_CLIPMAP_FRAME_SGIX,
        TextureClipmapLodOffsetSgix = Raw.GL_TEXTURE_CLIPMAP_LOD_OFFSET_SGIX,
        TextureClipmapOffsetSgix = Raw.GL_TEXTURE_CLIPMAP_OFFSET_SGIX,
        TextureClipmapVirtualDepthSgix = Raw.GL_TEXTURE_CLIPMAP_VIRTUAL_DEPTH_SGIX,
        TextureCompareSgix = Raw.GL_TEXTURE_COMPARE_SGIX,
        TextureLodBiasRSgix = Raw.GL_TEXTURE_LOD_BIAS_R_SGIX,
        TextureLodBiasSSgix = Raw.GL_TEXTURE_LOD_BIAS_S_SGIX,
        TextureLodBiasTSgix = Raw.GL_TEXTURE_LOD_BIAS_T_SGIX,
        TextureMagFilter = Raw.GL_TEXTURE_MAG_FILTER,
        TextureMaxClampRSgix = Raw.GL_TEXTURE_MAX_CLAMP_R_SGIX,
        TextureMaxClampSSgix = Raw.GL_TEXTURE_MAX_CLAMP_S_SGIX,
        TextureMaxClampTSgix = Raw.GL_TEXTURE_MAX_CLAMP_T_SGIX,
        TextureMinFilter = Raw.GL_TEXTURE_MIN_FILTER,
        TexturePriority = Raw.GL_TEXTURE_PRIORITY,
        TexturePriorityExt = Raw.GL_TEXTURE_PRIORITY_EXT,
        TextureWrapQSgis = Raw.GL_TEXTURE_WRAP_Q_SGIS,
        TextureWrapR = Raw.GL_TEXTURE_WRAP_R,
        TextureWrapRExt = Raw.GL_TEXTURE_WRAP_R_EXT,
        TextureWrapROes = Raw.GL_TEXTURE_WRAP_R_OES,
        TextureWrapS = Raw.GL_TEXTURE_WRAP_S,
        TextureWrapT = Raw.GL_TEXTURE_WRAP_T,
    }
    public enum TextureTarget : uint
    {
        DetailTextureTwoDSgis = Raw.GL_DETAIL_TEXTURE_2D_SGIS,
        ProxyTextureOneD = Raw.GL_PROXY_TEXTURE_1D,
        ProxyTextureOneDExt = Raw.GL_PROXY_TEXTURE_1D_EXT,
        ProxyTextureTwoD = Raw.GL_PROXY_TEXTURE_2D,
        ProxyTextureTwoDExt = Raw.GL_PROXY_TEXTURE_2D_EXT,
        ProxyTextureThreeD = Raw.GL_PROXY_TEXTURE_3D,
        ProxyTextureThreeDExt = Raw.GL_PROXY_TEXTURE_3D_EXT,
        ProxyTextureFourDSgis = Raw.GL_PROXY_TEXTURE_4D_SGIS,
        TextureOneD = Raw.GL_TEXTURE_1D,
        TextureTwoD = Raw.GL_TEXTURE_2D,
        TextureThreeD = Raw.GL_TEXTURE_3D,
        TextureThreeDExt = Raw.GL_TEXTURE_3D_EXT,
        TextureThreeDOes = Raw.GL_TEXTURE_3D_OES,
        TextureFourDSgis = Raw.GL_TEXTURE_4D_SGIS,
        TextureBaseLevel = Raw.GL_TEXTURE_BASE_LEVEL,
        TextureBaseLevelSgis = Raw.GL_TEXTURE_BASE_LEVEL_SGIS,
        TextureMaxLevel = Raw.GL_TEXTURE_MAX_LEVEL,
        TextureMaxLevelSgis = Raw.GL_TEXTURE_MAX_LEVEL_SGIS,
        TextureMaxLod = Raw.GL_TEXTURE_MAX_LOD,
        TextureMaxLodSgis = Raw.GL_TEXTURE_MAX_LOD_SGIS,
        TextureMinLod = Raw.GL_TEXTURE_MIN_LOD,
        TextureMinLodSgis = Raw.GL_TEXTURE_MIN_LOD_SGIS,
    }
    public enum TextureWrapMode : uint
    {
        Clamp = Raw.GL_CLAMP,
        ClampToBorder = Raw.GL_CLAMP_TO_BORDER,
        ClampToBorderArb = Raw.GL_CLAMP_TO_BORDER_ARB,
        ClampToBorderNv = Raw.GL_CLAMP_TO_BORDER_NV,
        ClampToBorderSgis = Raw.GL_CLAMP_TO_BORDER_SGIS,
        ClampToEdge = Raw.GL_CLAMP_TO_EDGE,
        ClampToEdgeSgis = Raw.GL_CLAMP_TO_EDGE_SGIS,
        Repeat = Raw.GL_REPEAT,
    }
    public enum UseProgramStageMask : uint
    {
        VertexShaderBit = Raw.GL_VERTEX_SHADER_BIT,
        VertexShaderBitExt = Raw.GL_VERTEX_SHADER_BIT_EXT,
        FragmentShaderBit = Raw.GL_FRAGMENT_SHADER_BIT,
        FragmentShaderBitExt = Raw.GL_FRAGMENT_SHADER_BIT_EXT,
        GeometryShaderBit = Raw.GL_GEOMETRY_SHADER_BIT,
        GeometryShaderBitExt = Raw.GL_GEOMETRY_SHADER_BIT_EXT,
        TessControlShaderBit = Raw.GL_TESS_CONTROL_SHADER_BIT,
        TessControlShaderBitExt = Raw.GL_TESS_CONTROL_SHADER_BIT_EXT,
        TessEvaluationShaderBit = Raw.GL_TESS_EVALUATION_SHADER_BIT,
        TessEvaluationShaderBitExt = Raw.GL_TESS_EVALUATION_SHADER_BIT_EXT,
        ComputeShaderBit = Raw.GL_COMPUTE_SHADER_BIT,
        AllShaderBits = Raw.GL_ALL_SHADER_BITS,
        AllShaderBitsExt = Raw.GL_ALL_SHADER_BITS_EXT,
    }
    public enum VertexPointerType : uint
    {
        Double = Raw.GL_DOUBLE,
        Float = Raw.GL_FLOAT,
        Int = Raw.GL_INT,
        Short = Raw.GL_SHORT,
    }
}
